<?php
/*****************************MIGAJAS****************************/
//MIGAJAS
$tabmenuCrumbsArray = 
	array(
	    TABMENU_PROCESOS_ADMINISTRATIVOS => array("Procesos Administrativos"),
		TABMENU_SOLICITUD_PAGOS => array("Solicitud de pagos"),
		TABMENU_COMPROBANTE_DIARIO => array("Contabilidad","Comprobante diario"),
		TABMENU_CONTABILIDAD_RETENCIONES => array("Contabilidad","Retenciones"),
		TABMENU_CONTABILIDAD_REPORTES => array("Contabilidad","Reportes"),
		TABMENU_PRESUPUESTO_PUNTO_CUENTA => array("Presupuesto","Punto de cuenta"),
		TABMENU_PRESUPUESTO_COMPROMISO => array("Presupuesto","Compromiso"),
		TABMENU_PRESUPUESTO_MODIFICACIONES_PRESUPUESTARIAS => array("Presupuesto","Modificaciones presupuestarias"),
		TABMENU_PRESUPUESTO_REPORTES => array("Presupuesto","Reportes"),
		TABMENU_TESORERIA_INICIAR_PAGO => array("Tesorer&iacute;a","Iniciar Pago"),	
		TABMENU_TESORERIA_PAGO_CHEQUE => array("Tesorer&iacute;a","Pago con cheque"),
		TABMENU_TESORERIA_PAGO_TRANSFERENCIA => array("Tesorer&iacute;a","Pago con transferencia"),		
		TABMENU_TESORERIA_REPORTES => array("Tesorer&iacute;a","Reportes"),
		TABMENU_TESORERIA_CONCILIACION_BANCARIA => array("Tesorer&iacute;a","Conciliaci&oacute;n"),
		TABMENU_COMPRAS_REQUISICION => array("Compras","Requisici&oacute;n"),		
		TABMENU_COMPRAS_SOLICITUD_COTIZACION => array("Compras","Solicitud de cotizaci&oacute;n"),
		TABMENU_COMPRAS_ORDEN_COMPRA => array("Compras","Orden de compra"),		
		TABMENU_VIATICOS_RENDICIONES_VIATICOS_NACIONALES => array("Vi&aacute;ticos/Rendiciones","Vi&aacute;ticos nacionales"),
		TABMENU_VIATICOS_RENDICIONES_AVANCES => array("Vi&aacute;ticos/Rendiciones","Avances"),
		TABMENU_VIATICOS_RENDICIONES_RENDICIONES_AVANCES => array("Vi&aacute;ticos/Rendiciones","Rendici&oacute;n de avances"),
		TABMENU_VIATICOS_RENDICIONES_RENDICIONES => array("Vi&aacute;ticos/Rendiciones","Rendici&oacute;n de vi&aacute;ticos nacionales"),		
		TABMENU_VIATICOS_RENDICIONES_VIATICOS_INTERNACIONALES => array("Vi&aacute;ticos/Rendiciones","Vi&aacute;ticos internacionales"),		
		TABMENU_COMUNICACIONES_MEMORANDOS => array("Comunicaciones", "Memorandos"),
		TABMENU_COMUNICACIONES_OFICIOS => array("Oficios"),
		TABMENU_BUSQUEDA => array("B&uacute;squeda"),		
		TABMENU_RECURSOS_EMPLEADO => array("Recursos","Empleado"),
		TABMENU_RECURSOS_USUARIO => array("Recursos","Usuario"),		
		TABMENU_RECURSOS_BANCOS => array("Recursos","Entidad bancaria","Bancos"),		
		TABMENU_RECURSOS_CUENTAS_BANCARIAS => array("Recursos","Entidad bancaria","Cuentas bancarias"),
		TABMENU_RECURSOS_PROVEEDORES => array("Recursos","Proveedor"),
		TABMENU_RECURSOS_SERVICIOS => array("Recursos","Servicio"),
		TABMENU_RECURSOS_PARTIDAS_PRESUPUESTARIAS => array("Recursos","Presupuesto","Partidas presupuestarias"),
		TABMENU_RECURSOS_CATEGORIA_PROGRAMATICA => array("Recursos","Presupuesto","Categor&iacute;a program&aacute;tica"),
		TABMENU_RECURSOS_ASIGNACION_PRESUPUESTO => array("Recursos","Presupuesto","Asignaci&oacute;n presupuestaria"),
		TABMENU_RECURSOS_MANEJO_ARTICULOS => array("Materiales","Administrar"),
		TABMENU_RECURSOS_MANEJO_INVENTARIO => array("Materiales","Inventario"),
		TABMENU_RECURSOS_ANULACION_ACTA_SALIDA => array("Materiales","Manejo de inventario","Anulaci&oacute;n acta salida"),
		TABMENU_RECURSOS_MANEJO_INVENTARIO_REPORTES => array("Materiales","Reportes"),
		TABMENU_RECURSOS_MANEJO_BIENES => array("Activos","Administrar"),
		TABMENU_RECURSOS_ACCIONES_BIEN => array("Activos","Entradas/Salidas"),
		TABMENU_RECURSOS_GARANTIA_BIEN => array ("Activos","Garant&iacute;a"),
		TABMENU_RECURSOS_REASIGNACION_BIEN => array ("Activos","Re-asignar"),
		TABMENU_RECURSOS_BIENES_REPORTES => array("Activos","Reportes"),
		TABMENU_RECURSOS_ACTIVOS_CATEGORIA => array("Recursos","Activos","Categor&iacute;as"),
		TABMENU_RECURSOS_ACTIVOS_MARCA => array("Recursos","Activos","Marcas"),
		TABMENU_RECURSOS_MATERIALES_CATEGORIA => array("Recursos","Materiales","Categor&iacute;as"),
		TABMENU_RECURSOS_CUSTODIA_BIEN => array("Activos","Custodia"),
		TABMENU_RECURSOS_CONTABILIDAD => array("Recursos","Contabilidad"),
		TABMENU_RECURSOS_MEMOS => array("Recursos","Memos"),		
		TABMENU_RECURSOS_CARGO => array("Recursos","Cargos"),		
		TABMENU_RECURSOS_VIATICOS_CATEGORIAS => array("Recursos","Vi&aacute;ticos","Categor&iacute;as"),
		TABMENU_MEMO => array("Memos", "Memo"),
		TABMENU_RECURSOS_RESP_SOCIAL_ADMINISTRAR => array("Responsabilidad Social","Administrar"),
		TABMENU_RECURSOS_RESP_SOCIAL_INVENTARIO => array("Responsabilidad Social","Inventario"),
		TABMENU_RECURSOS_RESP_SOCIAL_CUSTODIA => array ("Responsabilidad Social","Custodia"),
		TABMENU_RECURSOS_RESP_SOCIAL_REPORTES => array ("Responsabilidad Social","Reportes"),
		TABMENU_RECURSOS_RESP_SOCIAL_CATEGORIA=> array ("Recursos","Responsabilidad Social","Categor&iacute;as"),
		TABMENU_CAJA_CHICA_APERTURA => array("Caja chica", "Apertura")
	);
?>