<?php
//TABMENUS
/*Los valores de las constantes son las iniciales del nombre de la constante (en mayúscula).
 *Antes de agregar una nueva constante se debe verificar que el valor que se le va a colocar
 *no esté asignado a otra constante.
 */
//PROCESOS ADMINISTRATIVOS
define("TABMENU_PROCESOS_ADMINISTRATIVOS","TPA");

//SOLICITUD DE PAGOS
define("TABMENU_SOLICITUD_PAGOS","TSP");

//CONTABILIDAD
define("TABMENU_COMPROBANTE_DIARIO","TCTD");
define("TABMENU_CONTABILIDAD_RETENCIONES","TCTRT");
define("TABMENU_CONTABILIDAD_REPORTES","TCTR");

//PRESUPUESTO
define("TABMENU_PRESUPUESTO_COMPROMISO","TPC");
define("TABMENU_PRESUPUESTO_MODIFICACIONES_PRESUPUESTARIAS","TPMP");
define("TABMENU_PRESUPUESTO_PUNTO_CUENTA","TPPC");
define("TABMENU_PRESUPUESTO_REPORTES","TPR");

//TESORERIA
define("TABMENU_TESORERIA_CONCILIACION_BANCARIA","TTCB");
define("TABMENU_TESORERIA_INICIAR_PAGO","TTIP");
define("TABMENU_TESORERIA_PAGO_CHEQUE","TTPC");
define("TABMENU_TESORERIA_PAGO_TRANSFERENCIA","TTPT");
define("TABMENU_TESORERIA_REPORTES","TTR");

//COMPRAS
define("TABMENU_COMPRAS_ORDEN_COMPRA","TCOC");
define("TABMENU_COMPRAS_REQUISICION","TCR");
define("TABMENU_COMPRAS_SOLICITUD_COTIZACION","TCSC");

//VIATICOS/RENDICIONES
define("TABMENU_VIATICOS_RENDICIONES_AVANCES","TVRA");
define("TABMENU_VIATICOS_RENDICIONES_RENDICIONES","TVRR");
define("TABMENU_VIATICOS_RENDICIONES_VIATICOS_INTERNACIONALES","TVRVI");
define("TABMENU_VIATICOS_RENDICIONES_VIATICOS_NACIONALES","TVRVN");
define("TABMENU_VIATICOS_RENDICIONES_RENDICIONES_AVANCES","TVRRA");

//COMUNICACIONES
define("TABMENU_COMUNICACIONES_MEMORANDOS","TCM");
define("TABMENU_COMUNICACIONES_OFICIOS","TCO");

//MEMO
define("TABMENU_MEMO","TM");

//BUSQUEDA
define("TABMENU_BUSQUEDA","TB");

//RECURSOS
define("TABMENU_RECURSOS_ASIGNACION_PRESUPUESTO","TRAP");
define("TABMENU_RECURSOS_BANCOS","TRB");
define("TABMENU_RECURSOS_BIENES_REPORTES","TRBR");
define("TABMENU_RECURSOS_BUSCAR_BIEN","TRBB");
define("TABMENU_RECURSOS_CARGO","TRC");
define("TABMENU_RECURSOS_CATEGORIA_PROGRAMATICA","TRCP");
define("TABMENU_RECURSOS_CONTABILIDAD","TRCO");
define("TABMENU_RECURSOS_CUENTAS_BANCARIAS","TRCB");
define("TABMENU_RECURSOS_EMPLEADO","TRE");
define("TABMENU_RECURSOS_ACTIVOS_MARCA","TRAM");
define("TABMENU_RECURSOS_ACTIVOS_CATEGORIA","TRAC");
define("TABMENU_RECURSOS_MATERIALES_CATEGORIA","TRMAT");
define("TABMENU_RECURSOS_RESP_SOCIAL_CATEGORIA","TRRSC");

define("TABMENU_RECURSOS_MANEJO_BIENES","TRMB");
define("TABMENU_RECURSOS_ACCIONES_BIEN","TRIB");
define("TABMENU_RECURSOS_CUSTODIA_BIEN","TRCUB");
define("TABMENU_RECURSOS_GARANTIA_BIEN","TRGB");
define("TABMENU_RECURSOS_MANEJO_ARTICULOS","TRMA");
define("TABMENU_RECURSOS_RESP_SOCIAL_ADMINISTRAR","TRRSA");
define("TABMENU_RECURSOS_RESP_SOCIAL_INVENTARIO","TRRI");
define("TABMENU_RECURSOS_RESP_SOCIAL_CUSTODIA","TRRC");
define("TABMENU_RECURSOS_RESP_SOCIAL_REPORTES","TRRSR");
define("TABMENU_RECURSOS_MANEJO_INVENTARIO","TRMI");
define("TABMENU_RECURSOS_MEMOS","TRM");
define("TABMENU_RECURSOS_PARTIDAS_PRESUPUESTARIAS","TRPP");
define("TABMENU_RECURSOS_PROVEEDORES","TRP");
define("TABMENU_RECURSOS_SERVICIOS","TRS");
define("TABMENU_RECURSOS_USUARIO","TRU");
define("TABMENU_RECURSOS_VIATICOS_CATEGORIAS","TRVC");
define("TABMENU_RECURSOS_REASIGNACION_BIEN","TRRB");
define("TABMENU_RECURSOS_DESINCORPORACION_BIEN","TRDB");
//CAJA CHICA
define("TABMENU_CAJA_CHICA_APERTURA", "TMCCA");
//TABMENUITEMS

//PROCESOS ADMINISTRATIVOS
define("TABMENUITEM_PROCESOS_ADMINISTRATIVOS_REGISTRO","TIPAR");
define("TABMENUITEM_PROCESOS_ADMINISTRATIVOS_BUSQUEDA","TIPAB");

//SOLICITUD DE PAGOS
define("TABMENUITEM_SOLICITUD_PAGOS_BANDEJA","TISPBA");
define("TABMENUITEM_SOLICITUD_PAGOS_BUSQUEDA","TISPBU");
define("TABMENUITEM_SOLICITUD_PAGOS_ESTADIA","TISPES");
define("TABMENUITEM_SOLICITUD_PAGOS_COMPROBANTE_RETENCION","TISPCR");
define("TABMENUITEM_SOLICITUD_PAGOS_INSERTAR","TISPI");
define("TABMENUITEM_SOLICITUD_PAGOS_ANULACION","TISPR");


//CONTABILIDAD COMPROBANTE DIARIO
define("TABMENUITEM_COMPROBANTE_DIARIO_INSERTAR","TICDI");
define("TABMENUITEM_COMPROBANTE_DIARIO_BUSQUEDA","TICDBU");

//CONTABILIDAD RETENCIONES
define("TABMENUITEM_CONTABILIDAD_RETENCIONES","TICRT");
define("TABMENUITEM_CONTABILIDAD_DISQUETE","TICTD");
define("TABMENUITEM_CONTABILIDAD_ARCV","TICARCV");

//CONTABILIDAD REPORTES
define("TABMENUITEM_REPORTES_BALANCE_COMPROBACION","TIRBC");
define("TABMENUITEM_REPORTES_CODA_ANULADO","TIRCA");
define("TABMENUITEM_REPORTES_CONTABILIDAD_DOCUMENTO","TIRCD");
define("TABMENUITEM_REPORTES_ESTADO_RESULTADOS","TIRER");
define("TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO1","TIRFF1");
define("TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO2","TIRFF2");
define("TABMENUITEM_REPORTES_MAYOR_ANALITICO","TIRMA");
define("TABMENUITEM_REPORTES_AUXILIAE","TIAUX");
define("TABMENUITEM_REPORTES_CAUSADO","TIRC");
define("TABMENUITEM_REPORTES_GESTIONTRANSF","TIRGT");


//PRESUPUESTO PUNTO DE CUENTA
define("TABMENUITEM_PUNTO_CUENTA_BANDEJA","TIPCBA");
define("TABMENUITEM_PUNTO_CUENTA_BUSQUEDA","TIPCBU");
define("TABMENUITEM_PUNTO_CUENTA_INSERTAR","TIPCI");
define("TABMENUITEM_PUNTO_CUENTA_LIBERACION","TIPCL");
define("TABMENUITEM_PUNTO_CUENTA_ESTADIA","TIPCE");
define("TABMENUITEM_PUNTO_CUENTA_DISPONIBILIDAD","TIPDI");

//PRESUPUESTO COMPROMISO
define("TABMENUITEM_COMPROMISO_INSERTAR","TICI");
define("TABMENUITEM_COMPROMISO_BUSQUEDA","TICBU");
define("TABMENUITEM_COMPROMISO_VARIACION","TICV");
define("TABMENUITEM_COMPROMISO_REPORTE","TICR");
define("TABMENUITEM_COMPROMISO_PROVEEDOR","TICP");
define("TABMENUITEM_COMPROMISO_PROVEEDOR_DETALLADO","TICPD");
define("TABMENUITEM_COMPROMISO_CAUSADO_PAGADO","TICCP");
define("TABMENUITEM_COMPROMISO_REPORTE_ACTIVIDAD","TICRA");

//PRESUPUESTO MODIFICACIONES PRESUPUESTARIAS
define("TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BANDEJA","TIMPBA");
define("TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_INSERTAR","TIMPI");
define("TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BUSQUEDA","TIMPBU");

//TESORERIA REPORTES
define("TABMENUITEM_TESORERIA_PAGO_CHEQUE_BANDEJA","TITPCB");
define("TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_BANDEJA","TITTB");
define("TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_MODIFICAR","TITTMO");
define("TABMENUITEM_REPORTES_BUSQUEDA_MULTIPLE","TIRBUM");
define("TABMENUITEM_REPORTES_OPERACIONES_EMITIDAS","TIROE");
define("TABMENUITEM_REPORTES_SALDOS_CORRECTOS","TIRSC");
define("TABMENUITEM_REPORTES_RELACION_CONTABILIDAD","TIRRC");
define("TABMENUITEM_REPORTES_UBICAR_DOCUMENTO","TIRUD");
//TESORERIA CONCILIACION BANCARIA
define("TABMENUITEM_CONCILIACION_BANCARIA_ANULAR","TICBA");
define("TABMENUITEM_CONCILIACION_BANCARIA_CONCILIAR","TICBC");

//COMPRAS REQUISICION
define("TABMENUITEM_REQUISICION_BANDEJA","TIRBA");
define("TABMENUITEM_REQUISICION_BUSQUEDA","TIRBU");
define("TABMENUITEM_REQUISICION_ESTADIA","TIRES");
define("TABMENUITEM_REQUISICION_INSERTAR","TIRI");
//COMPRAS SOLICITUD COTIZACION
define("TABMENUITEM_SOLICITUD_COTIZACION_BUSQUEDA","TISCBU");
//COMPRAS ORDEN DE COMPRA
define("TABMENUITEM_ORDEN_COMPRA_BANDEJA","TIOCBA");
define("TABMENUITEM_ORDEN_COMPRA_BUSQUEDA","TIOCBU");
define("TABMENUITEM_ORDEN_COMPRA_INSERTAR","TIOCI");
define("TABMENUITEM_ORDEN_COMPRA_ESTADIA","TIOCES");

//VIATICOS/RENDICIONES VIATICOS NACIONALES
define("TABMENUITEM_VIATICOS_NACIONALES_BANDEJA","TIVNBA");
define("TABMENUITEM_VIATICOS_NACIONALES_BUSQUEDA","TIVNBU");
define("TABMENUITEM_VIATICOS_NACIONALES_INSERTAR","TIVNI");
define("TABMENUITEM_VIATICOS_NACIONALES_REPORTE_1","TIVNR1");
define("TABMENUITEM_VIATICOS_NACIONALES_REPORTE_RESPONSABLES","TIVNRR");
//VIATICOS/RENDICIONES AVANCES
define("TABMENUITEM_AVANCES_BANDEJA","TIABA");
define("TABMENUITEM_AVANCES_BUSQUEDA","TIABU");
define("TABMENUITEM_AVANCES_INSERTAR","TIAI");
define("TABMENUITEM_AVANCES_ARCHIVOS_PAGOS","TIAAP");
define("TABMENUITEM_AVANCES_REPORTE_RESPONSABLES","TIARR");
//VIATICOS/RENDICIONES RENDICIONES AVANCES
define("TABMENUITEM_RENDICIONES_AVANCES_BANDEJA","TIRABA");
define("TABMENUITEM_RENDICIONES_AVANCES_BUSQUEDA","TIRABU");
define("TABMENUITEM_RENDICIONES_AVANCES_INSERTAR","TIRAI");
//VIATICOS/RENDICIONES RENDICIONES
define("TABMENUITEM_RENDICIONES_BANDEJA","TIRENBA");
define("TABMENUITEM_RENDICIONES_BUSQUEDA","TIRENBU");
define("TABMENUITEM_RENDICIONES_INSERTAR","TIRENI");
//VIATICOS/RENDICIONES VIATICOS INTERNACIONALES
define("TABMENUITEM_VIATICOS_INTERNACIONALES_BANDEJA","TIVIBA");
define("TABMENUITEM_VIATICOS_INTERNACIONALES_BUSQUEDA","TIVIBU");
define("TABMENUITEM_VIATICOS_INTERNACIONALES_INSERTAR","TIVII");

//COMUNICACIONES/MEMORANDOS
define("TABMENUITEM_COMUNICACIONES_MEMORANDOS_INSERTAR","TICMI");
define("TABMENUITEM_COMUNICACIONES_MEMORANDOS_BANDEJA","TICMB");
//COMUNICACIONES/OFICIOS
define("TABMENUITEM_COMUNICACIONES_OFICIOS_INSERTAR","TICOI");
define("TABMENUITEM_COMUNICACIONES_OFICIOS_BANDEJA","TICOB");

//MEMO
define("TABMENUITEM_MEMO","TIM");

//BUSQUEDA
define("TABMENUITEM_BUSQUEDA_UBICAR_DOCUMENTO","TIBUD");

//RECURSOS EMPLEADO
define("TABMENUITEM_EMPLEADO_BUSCAR_EMPLEADOS","TIEBEM");
define("TABMENUITEM_EMPLEADO_BUSCAR_OTROS_TRABAJADORES","TIEBOT");
define("TABMENUITEM_EMPLEADO_GESTIONAR_EMPLEADO","TIEGE");
define("TABMENUITEM_EMPLEADO_GESTIONAR_OTROS_TRABAJADORES","TIEGOT");
//RECURSOS USUARIO
define("TABMENUITEM_USUARIO_BUSCAR","TIUB");
define("TABMENUITEM_USUARIO_CONTRASENA","TIUC");
define("TABMENUITEM_USUARIO_GESTIONAR","TIUG");
//RECURSOS BANCOS
define("TABMENUITEM_BANCOS_BUSCAR","TIBB");
define("TABMENUITEM_BANCOS_GESTIONAR","TIBG");
//RECURSOS CUENTAS BANCARIAS
define("TABMENUITEM_CUENTAS_BANCARIAS_BUSCAR","TICBB");
define("TABMENUITEM_CUENTAS_BANCARIAS_GESTIONAR","TICBG");
//RECURSOS PARTIDAS PRESUPUESTARIAS
define("TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BUSCAR","TIPPB");
define("TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_INSERTAR","TIPPI");
define("TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BIENES","TIPBI");
//RECURSOS CATEGORIA PROGRAMATICA
define("TABMENUITEM_CATEGORIA_PROGRAMATICA_BUSCAR","TICPB");
define("TABMENUITEM_CATEGORIA_PROGRAMATICA_INSERTAR","TICPI");
//RECURSOS ASIGNACION PRESUPUESTARIA
define("TABMENUITEM_ASIGNACION_PRESUPUESTO_INSERTAR","TIAPI");
define("TABMENUITEM_ASIGNACION_PRESUPUESTO_BUSCAR","TIAPBU");
//RECURSOS MANEJO DE INVENTARIO REPORTES
define("TABMENUITEM_MANEJO_INVENTARIO_REPORTES_INVENTARIO_ACTUALIZADO","TIMIRIA");
define("TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_ARTICULO","TIMIRMA");
define("TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_FECHA","TIMIRMF");
define("TABMENUITEM_MANEJO_INVENTARIO_REPORTES_ACTAS","TIMIRA");
define("TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_BUSCAR","TIMIRG");
define("TABMENUITEM_MANEJO_INVENTARIO_REPORTES_COMPRAS_CONSUMO","TIMIRCC");
//RECURSOS BIENES REPORTES
define("TABMENUITEM_BIENES_REPORTES_ACTIVOS_ADQUIRIDOS","TIBRAA");
define("TABMENUITEM_BIENES_REPORTES_INVENTARIO_ACTIVOS","TIBRIA");
define("TABMENUITEM_BIENES_REPORTES_CUSTODIA","TIBRC");
define("TABMENUITEM_BIENES_REPORTES_ACTAS","TIBRA");
define("TABMENUITEM_BIENES_REPORTES_SALIDAS","TIBRS");
define("TABMENUITEM_BIENES_REPORTES_ENTREGA","TIBRE");
define("TABMENUITEM_BIENES_REPORTES_GARANTIA","TIBRG");

//RECURSOS CONTABILIDAD
define("TABMENUITEM_CONTABILIDAD_BUSCAR_CONVERTIDOR","TICONBC");
define("TABMENUITEM_CONTABILIDAD_BUSCAR_CUENTAS_CONTABLES","TICONBCC");
define("TABMENUITEM_CONTABILIDAD_INGRESAR_CONVERTIDOR","TICONIC");
define("TABMENUITEM_CONTABILIDAD_INGRESAR_CUENTAS_CONTABLES","TICONICC");
//RECURSOS VIATICOS CATEGORIAS
define("TABMENUITEM_VIATICOS_CATEGORIAS_BUSCAR_CATEGORIAS","TIVCBC");
define("TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR","TIVCG");
define("TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR_ASIGNACIONES","TIVCGA");

//RECURSOS PROVEEDORES
define("TABMENUITEM_PROVEEDORES_BUSCAR","TIPB");
define("TABMENUITEM_PROVEEDORES_GESTIONAR","TIPG");
define("TABMENUITEM_PROVEEDORES_REPORTES","TIPR");

//RECURSOS SERVICIOS
define("TABMENUITEM_SERVICIOS_BUSCAR","TISB");
define("TABMENUITEM_SERVICIOS_INSERTAR","TISI");

//RECURSOS CARGOS
define("TABMENUITEM_CARGO_GESTIONAR","TICARG");
define("TABMENUITEM_CARGO_BUSCAR","TICARB");

//RECURSOS ALMACEN MANEJO ARTICULOS
define("TABMENUITEM_MANEJO_ARTICULO_BUSCAR","TIMAB");
define("TABMENUITEM_MANEJO_ARTICULO_GESTIONAR","TIMAG");
define("TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_INGRESAR","TIMCMI");
define("TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_BUSCAR","TIMCAB");

//RECURSOS RESPONSABILIDAD SOCIAL_ADMINISTRAR
define("TABMENUITEM_RESP_SOCIAL_GESTIONAR","TIRSG");
define("TABMENUITEM_RESP_SOCIAL_BUSCAR","TIRSB");

//RECURSOS RESPONSABILIDAD SOCIAL_INVENTARIO
define("TABMENUITEM_RESP_SOCIAL_BANDEJA","TIRSBA");
define("TABMENUITEM_RESP_SOCIAL_INGRESAR","TIRSI");
define("TABMENUITEM_RESP_SOCIAL_ASIGNAR","TIRSA");
define("TABMENUITEM_RESP_SOCIAL_BUSCAR","TIRSB");

//RECURSOS RESPONSABILIDAD SOCIAL_CUSTODIA
define("TABMENUITEM_RESP_SOCIAL_CUSTODIA","TIRSCU");

//RECURSOS RESPONSABILIDAD SOCIAL_REPORTES
define("TABMENUITEM_RESP_SOCIAL_REPORTES_INVENTARIO","TIRSRI");

//RECURSOS ALMACEN MANEJO INVENTARIO
define("TABMENUITEM_MANEJO_INVENTARIO_CARGA_BANDEJA","TIMICB");
define("TABMENUITEM_MANEJO_INVENTARIO_CARGA","TIMIC");
define("TABMENUITEM_MANEJO_INVENTARIO_DISMINUCION","TIMID");
define("TABMENUITEM_MANEJO_INVENTARIO_MODIFICACION","TIMIM");
define("TABMENUITEM_MANEJO_INVENTARIO_SALIDA","TIMIS");

//RECURSOS BIENES
define("TABMENUITEM_MANEJO_BIEN_INGRESAR","TIMBI");
define("TABMENUITEM_MANEJO_BIEN_BUSCAR","TIMBB");
define("TABMENUITEM_MANEJO_MARCA_INGRESAR","TIMMI");
define("TABMENUITEM_MANEJO_MARCA_BUSCAR","TIMMB");
define("TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_INGRESAR","TIMCAI");
define("TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_BUSCAR","TIMCAB");
define("TABMENUITEM_ACCIONES_BANDEJA_BIEN","TIMBB");
define("TABMENUITEM_ACCIONES_INCORPORAR_BIEN","TIMIB");
define("TABMENUITEM_ACCIONES_SALIDAS_BIEN","TIMSB");
define("TABMENUITEM_CUSTODIA_BIEN","TICB");
define("TABMENUITEM_GARANTIA_BIEN","TIGB");
define("TABMENUITEM_GARANTIA_BIEN_BUSCAR","TIGBB");
define("TABMENUITEM_RECURSOS_REASIGNACION_BIEN","TIRRB");
define("TABMENUITEM_RECURSOS_REASIGNACION_BIEN_BUSCAR","TIRRBB");
define("TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BANDEJA","TIRDBA");
define("TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BUSCAR","TIRDBU");
define("TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_REGISTRAR","TIRDRE");

//RECURSOS RESPONSABILIDAD SOCIAL
define("TABMENUITEM_RESP_SOCIAL_CATEGORIA_INGRESAR","TIRSCI");
define("TABMENUITEM_RESP_SOCIAL_CATEGORIA_BUSCAR","TIRSCB");

//CAJA CHICA
define("TABMENUITEM_CAJA_CHICA_APERTURA_INSERTAR", "TICCAI");

?>