<?php
/*****************************TABMENU****************************/

//TABMENU. PARA INDEXAR LOS VALORES DE LOS TABMENUITEMS USAR: 'ID','NOMBRE','URL', 'PERFILES'
$tabmenuItemsArray = 
	array(
	    TABMENU_PROCESOS_ADMINISTRATIVOS =>
	    array(
			TABMENUITEM_PROCESOS_ADMINISTRATIVOS_REGISTRO => array("ID" => TABMENUITEM_PROCESOS_ADMINISTRATIVOS_REGISTRO, "NOMBRE" => "Registro Documento", "URL" => "procesos/contabilidad/registro/registroDocumento.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO_ADMINISTRACION, PERFIL_ASISTENTE_ADMINISTRATIVO_OTH, PERFIL_ASISTENTE_PRESUPUESTO)),
			TABMENUITEM_PROCESOS_ADMINISTRATIVOS_BUSQUEDA => array("ID" => TABMENUITEM_PROCESOS_ADMINISTRATIVOS_BUSQUEDA, "NOMBRE" => "Buscar Documento", "URL" => "procesos/contabilidad/registro/buscar.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO_ADMINISTRACION, PERFIL_ASISTENTE_ADMINISTRATIVO_OTH, PERFIL_ASISTENTE_PRESUPUESTO))	    
	    ),
	
		TABMENU_SOLICITUD_PAGOS => 
		array(
			TABMENUITEM_SOLICITUD_PAGOS_INSERTAR => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_INSERTAR, "NOMBRE" => "Insertar", "URL" => "acciones/sopg/sopg.php?accion=Ingresar", "PERFILES" => array(PERFIL_ANALISTA_ORDENACION_PAGOS)),
			TABMENUITEM_SOLICITUD_PAGOS_BANDEJA => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos.php?tipo=sopg", "PERFILES" => array(PERFIL_ANALISTA_ORDENACION_PAGOS,PERFIL_COORDINADOR_ORDENACION_PAGOS,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),
			//TABMENUITEM_SOLICITUD_PAGOS_INSERTAR => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_INSERTAR, "NOMBRE" => "Insertar", "URL" => "accion_documento.php?accion=1&tipo=sopg", "PERFILES" => array(PERFIL_ANALISTA_ORDENACION_PAGOS)),
			TABMENUITEM_SOLICITUD_PAGOS_BUSQUEDA => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "documentos/sopg/sopg_buscar.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_ANALISTA_ORDENACION_PAGOS,PERFIL_COORDINADOR,PERFIL_JEFE,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_ANALISTA_CONTABLE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE)),
			TABMENUITEM_SOLICITUD_PAGOS_ESTADIA => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_ESTADIA, "NOMBRE" => "Estad&iacute;a", "URL" => "documentos/sopg/sopg_estadia.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_ANALISTA_ORDENACION_PAGOS,PERFIL_COORDINADOR,PERFIL_JEFE,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_ANALISTA_CONTABLE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE)),
			TABMENUITEM_SOLICITUD_PAGOS_COMPROBANTE_RETENCION => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_COMPROBANTE_RETENCION, "NOMBRE" => "Comprobante retenci&oacute;n", "URL" => "documentos/sopg/comprobantes/index_comprobantes.php", "PERFILES" => array(PERFIL_ANALISTA_ORDENACION_PAGOS)),
			TABMENUITEM_SOLICITUD_PAGOS_ANULACION => array("ID" => TABMENUITEM_SOLICITUD_PAGOS_ANULACION, "NOMBRE" => "Anulaci&oacute;n", "URL" => "documentos/sopg/sopg_aprobados.php", "PERFILES" => array(PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS))
			),
		TABMENU_COMPROBANTE_DIARIO => 
		array(
			TABMENUITEM_COMPROBANTE_DIARIO_INSERTAR => array("ID" => TABMENUITEM_COMPROBANTE_DIARIO_INSERTAR, "NOMBRE" => "Registrar", "URL" => "acciones/codi/codi.php?accion=Registrar", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD)),				
			//TABMENUITEM_COMPROBANTE_DIARIO_INSERTAR => array("ID" => TABMENUITEM_COMPROBANTE_DIARIO_INSERTAR, "NOMBRE" => "Registrar", "URL" => "documentos/codi/codi_1.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD)),
			//TABMENUITEM_COMPROBANTE_DIARIO_BUSQUEDA => array("ID" => TABMENUITEM_COMPROBANTE_DIARIO_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "documentos/codi/buscar_codi.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_JEFE_ORDENACION_CONTABILIDAD, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS))
			TABMENUITEM_COMPROBANTE_DIARIO_BUSQUEDA => array("ID" => TABMENUITEM_COMPROBANTE_DIARIO_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "acciones/codi/codi.php?accion=Buscar", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_JEFE_ORDENACION_CONTABILIDAD, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS))			
			), 
		
		TABMENU_CONTABILIDAD_RETENCIONES => 
		array(
			TABMENUITEM_CONTABILIDAD_RETENCIONES  => array("ID" => TABMENUITEM_CONTABILIDAD_RETENCIONES, "NOMBRE" => "Retenciones", "URL" => "procesos/contabilidad/retenciones/index.php", "PERFILES" => array()),
			TABMENUITEM_CONTABILIDAD_DISQUETE => array("ID" => TABMENUITEM_CONTABILIDAD_DISQUETE, "NOMBRE" => "Disquete SENIAT", "URL" => "procesos/contabilidad/retenciones/disquete.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD)),
			TABMENUITEM_CONTABILIDAD_ARCV => array("ID" => TABMENUITEM_CONTABILIDAD_ARCV, "NOMBRE" => "ARCV", "URL" => "procesos/contabilidad/retenciones/busqueda_arcv.php", "PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD))
			 ),
		TABMENU_CONTABILIDAD_REPORTES => 
		array(
			TABMENUITEM_REPORTES_CONTABILIDAD_DOCUMENTO => array("ID" => TABMENUITEM_REPORTES_CONTABILIDAD_DOCUMENTO, "NOMBRE" => "Contabilidad x Doc.", "URL" => "reportes/contabilidad/contabilidadDocumento.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS, PERFIL_JEFE_FINANZAS)),		
			TABMENUITEM_REPORTES_MAYOR_ANALITICO_2 => array("ID" => TABMENUITEM_REPORTES_MAYOR_ANALITICO_2, "NOMBRE" => "Mayor anal&iacute;tico", "URL" => "reportes/contabilidad/mayorAnalitico_2.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR, PERFIL_JEFE_FINANZAS)),			
			TABMENUITEM_REPORTES_ESTADO_RESULTADOS => array("ID" => TABMENUITEM_REPORTES_ESTADO_RESULTADOS, "NOMBRE" => "Balance Gral/Edo. Resultados", "URL" => "reportes/contabilidad/balanceGeneral.php?tipoReporte=1", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR, PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_REPORTES_BALANCE_COMPROBACION => array("ID" => TABMENUITEM_REPORTES_BALANCE_COMPROBACION, "NOMBRE" => "Balance de comprobaci&oacute;n", "URL" => "reportes/contabilidad/balanceComprobacion.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR, PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_REPORTES_AUXILIAR => array("ID" => TABMENUITEM_REPORTES_AUXILIAR, "NOMBRE" => "Auxiliar", "URL" => "reportes/contabilidad/auxiliar.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),			
			TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO1 => array("ID" => TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO1, "NOMBRE" => "Mov. banc/pres", "URL" => "acciones/reportes/contabilidad/reportesContabilidad.php?accion=cuentaBancariaPagado", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR)),
			TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO2 => array("ID" => TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO2, "NOMBRE" => "Mov. consolidado", "URL" => "acciones/reportes/contabilidad/reportesContabilidad.php?accion=cuentaCausadoPagado", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR, PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			//TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO => array("ID" => TABMENUITEM_REPORTES_FUENTE_FINANCIAMIENTO, "NOMBRE" => "Movimientos bancarios/presupuestarios", "URL" => "reportes/contabilidad/fuenteFinanciamiento.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR)),			
			TABMENUITEM_REPORTES_CODA_ANULADO => array("ID" => TABMENUITEM_REPORTES_CODA_ANULADO, "NOMBRE" => "Codas Anulados", "URL" => "reportes/contabilidad/codaAnulados.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_AUDITOR)),
			TABMENUITEM_REPORTES_CAUSADO => array("ID" => TABMENUITEM_REPORTES_CAUSADO,"NOMBRE" => "Causado/Pagado","URL"=> "reportes/contabilidad/reporte_causadopagado.php","PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),
			TABMENUITEM_REPORTES_GESTIONTRANSF => array("ID" => TABMENUITEM_REPORTES_GESTIONTRANSF,"NOMBRE" => "Gesti&oacute;n pagos","URL"=> "reportes/contabilidad/reporteTransferencias.php","PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD)),			
			//TABMENUITEM_REPORTES_PAGADO => array("ID" => TABMENUITEM_REPORTES_PAGADO,"NOMBRE" => "Pagado","URL"=> "reportes/contabilidad/reporte_pagado.php","PERFILES" => array())	
			),
		TABMENU_PRESUPUESTO_PUNTO_CUENTA => 
				array(
			TABMENUITEM_PUNTO_CUENTA_BANDEJA => array("ID" => TABMENUITEM_PUNTO_CUENTA_BANDEJA,"NOMBRE" => "Bandeja", "URL" => "acciones/pcta/pcta.php?accion=Bandeja", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_JEFE,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_COORDINADOR,PERFIL_COORDINADOR_NACIONAL,PERFIL_COORDINADOR_NACIONAL_MOVIL,PERFIL_ASISTENTE_PRESIDENCIA)),
			TABMENUITEM_PUNTO_CUENTA_INSERTAR => array("ID" => TABMENUITEM_PUNTO_CUENTA_INSERTAR, "NOMBRE" => "Registrar", "URL" => "acciones/pcta/pcta.php?accion=Ingresar", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ASISTENTE_PRESIDENCIA)),
			TABMENUITEM_PUNTO_CUENTA_BUSQUEDA => array("ID" => TABMENUITEM_PUNTO_CUENTA_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "acciones/pcta/pcta.php?accion=Buscar", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_JEFE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_COORDINADOR,PERFIL_COORDINADOR_NACIONAL,PERFIL_COORDINADOR_NACIONAL_MOVIL,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_ANALISTA_CONTABLE,PERFIL_ASISTENTE_PRESIDENCIA)),
			//TABMENUITEM_PUNTO_CUENTA_LIBERACION => array("ID" => TABMENUITEM_PUNTO_CUENTA_LIBERACION, "NOMBRE" => "Liberaci&oacute;n", "URL" => "documentos/pcta/pcta_liberacion.php", "PERFILES" => array(PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO)),
		   TABMENUITEM_PUNTO_CUENTA_DISPONIBILIDAD => array("ID" => TABMENUITEM_PUNTO_CUENTA_DISPONIBILIDAD, "NOMBRE" => "Disponibilidad", "URL" =>"acciones/pcta/pcta.php?accion=reporteDisponibleIntegrado", "PERFILES"=> array(PERFIL_ANALISTA_PRESUPUESTO,PERFIL_GERENTE,PERFIL_JEFE_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_JEFE, PERFIL_COORDINADOR, PERFIL_COORDINADOR_NACIONAL_MOVIL)),
			
			),
		TABMENU_PRESUPUESTO_COMPROMISO => 
		array(
		   
		   TABMENUITEM_COMPROMISO_VARIACION => array("ID" => TABMENUITEM_COMPROMISO_VARIACION, "NOMBRE" => "Variaci&oacute;n", "URL" =>"acciones/comp/comp.php?accion=Variacion", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO)),
		   TABMENUITEM_COMPROMISO_REPORTE => array("ID" => TABMENUITEM_COMPROMISO_REPORTE, "NOMBRE" => "Control Interno", "URL" => "documentos/comp/comp_reporte.php", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_AUDITOR)),
		   TABMENUITEM_COMPROMISO_PROVEEDOR => array("ID" => TABMENUITEM_COMPROMISO_PROVEEDOR, "NOMBRE" => "Proveedor", "URL" => "documentos/comp/comp_proveedor.php", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_AUDITOR, PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD)),
		   
		   TABMENUITEM_COMPROMISO_CAUSADO_PAGADO => array("ID" => TABMENUITEM_COMPROMISO_CAUSADO_PAGADO, "NOMBRE" => "Causado/Pagado", "URL" => "acciones/comp/comp.php?accion=CausadoPagado", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_AUDITOR)),
		   TABMENUITEM_COMPROMISO_INSERTAR => array("ID" => TABMENUITEM_COMPROMISO_INSERTAR, "NOMBRE" => "Insertar", "URL" => "acciones/comp/comp.php?accion=Ingresar", "PERFILES" => array(PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO)),
		   TABMENUITEM_COMPROMISO_BUSQUEDA => array("ID" => TABMENUITEM_COMPROMISO_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "acciones/comp/comp.php?accion=Buscar", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),
		   
		   //TABMENUITEM_COMPROMISO_BUSQUEDA => array("ID" => TABMENUITEM_COMPROMISO_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "documentos/comp/comp_buscar.php", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),
		   //TABMENUITEM_COMPROMISO_VARIACION => array("ID" => TABMENUITEM_COMPROMISO_VARIACION, "NOMBRE" => "Variaci&oacute;n", "URL" =>"documentos/comp/comp_variacion.php", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO)),
		   //TABMENUITEM_COMPROMISO_CAUSADO_PAGADO => array("ID" => TABMENUITEM_COMPROMISO_CAUSADO_PAGADO, "NOMBRE" => "Causado/Pagado", "URL" => "documentos/comp/comp_causado_pagado.php", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_AUDITOR)),
		   	
			
			TABMENUITEM_COMPROMISO_REPORTE_ACTIVIDAD => array("ID" => TABMENUITEM_COMPROMISO_REPORTE_ACTIVIDAD, "NOMBRE" => "Reporte Actividad", "URL" => "acciones/comp/comp.php?accion=ReporteActividad", "PERFILES" => array(PERFIL_DIRECTOR_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO,PERFIL_AUDITOR))
			
			
			),
		TABMENU_PRESUPUESTO_MODIFICACIONES_PRESUPUESTARIAS => 
		array(
		
			//TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BANDEJA => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos.php?tipo=pmod", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			//TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_INSERTAR => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_INSERTAR, "NOMBRE" => "Insertar", "URL" => "accion_documento.php?accion=1&tipo=pmod", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			//TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BUSQUEDA => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "documentos/pmod/buscar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			

			TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_INSERTAR => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_INSERTAR, "NOMBRE" => "Registrar", "URL" => "acciones/modificacionespresupuestarias/mpresupuestarias.php?accion=Ingresar", "PERFILES" => array(PERFIL_ANALISTA_PRESUPUESTO)),
			TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BANDEJA => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "acciones/modificacionespresupuestarias/mpresupuestarias.php?accion=Bandeja", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO)),
			TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BUSQUEDA => array("ID" => TABMENUITEM_MODIFICACIONES_PRESUPUESTARIAS_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "acciones/modificacionespresupuestarias/mpresupuestarias.php?accion=Buscar", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO))
			
			
			),
		TABMENU_PRESUPUESTO_REPORTES => 
		array(
			TABMENUITEM_DISPONIBILIDAD_PRESUPUESTARIA => array("ID" => TABMENUITEM_DISPONIBILIDAD_PRESUPUESTARIA, "NOMBRE" => "Disponibilidad presupuestaria", "URL" => "reportes/presupuesto/disponibilidad.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ASISTENTE_ADMINISTRATIVO, PERFIL_ASISTENTE_EJECUTIVO, PERFIL_ASISTENTE_PRESIDENCIA, PERFIL_GERENTE, PERFIL_DIRECTOR, PERFIL_ANALISTA_CONTABLE,PERFIL_JEFE, PERFIL_COORDINADOR_NACIONAL_MOVIL,PERFIL_AUDITOR,PERFIL_ANALISTA_ORDENACION_PAGOS,PERFIL_COORDINADOR_ORDENACION_PAGOS)),
			TABMENUITEM_MOMENTOS_PRESUPUESTARIOS => array("ID" => TABMENUITEM_MOMENTOS_PRESUPUESTARIOS, "NOMBRE" => "Momentos presupuestarios", "URL" => "reportes/presupuesto/momentoPresupuestario.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_CONTABLE,PERFIL_AUDITOR)),
			TABMENUITEM_EJECUCION_PRESUPUESTARIA => array("ID" => TABMENUITEM_EJECUCION_PRESUPUESTARIA, "NOMBRE" => "Ejecuci&oacute;n Trimestral", "URL" => "reportes/presupuesto/ejecucionTrimestral.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_CONTABLE,PERFIL_AUDITOR))
			),	
		TABMENU_TESORERIA_PAGO_CHEQUE => 
		array(
			TABMENUITEM_TESORERIA_PAGO_CHEQUE_BANDEJA => array("ID" => TABMENUITEM_TESORERIA_PAGO_CHEQUE_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos.php?tipo=pgch", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_TESORERIA_PAGO_CHEQUE_INICIAR => array("ID" => TABMENUITEM_TESORERIA_PAGO_CHEQUE_INICIAR, "NOMBRE" => "Iniciar pago (tran)", "URL" => "acciones/pgch/pgch.php?accion=Iniciar", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),				
			TABMENUITEM_TESORERIA_PAGO_CHEQUE_ACTUALIZAR => array("ID" => TABMENUITEM_TESORERIA_PAGO_CHEQUE_ACTUALIZAR, "NOMBRE" => "Actualizar beneficiario cheque", "URL" => "acciones/pgch/pgch.php?accion=ActualizarBeneficiarioCheque", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),				
			),
		TABMENU_TESORERIA_PAGO_TRANSFERENCIA => 
		array(
			TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_BANDEJA => array("ID" => TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos.php?tipo=tran", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_ANULAR => array("ID" => TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_ANULAR, "NOMBRE" => "Anular", "URL" => "documentos/tran/anularTran.php?tipo=tran", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),			
//			TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_MODIFICAR => array("ID" => TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_MODIFICAR, "NOMBRE" => "Modificar", "URL" => "documentos/tran/modificarTran.php?tipo=tran", "PERFILES" => array(PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_MODIFICAR => array("ID" => TABMENUITEM_TESORERIA_PAGO_TRANSFERENCIA_MODIFICAR, "NOMBRE" => "Modificar", "URL" => "acciones/tran/transferencia.php?accion=Modificar", "PERFILES" => array(PERFIL_TESORERO, PERFIL_JEFE_FINANZAS)),				
				
			),					
			
		TABMENU_TESORERIA_REPORTES => 
		array(
			TABMENUITEM_REPORTES_BUSQUEDA_MULTIPLE => array("ID" => TABMENUITEM_REPORTES_BUSQUEDA_MULTIPLE, "NOMBRE" => "Buscar", "URL" => "acciones/reportes/tesoreria/reportesTesoreria.php?accion=Buscar", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS, PERFIL_ANALISTA_TESORERIA)),
			TABMENUITEM_REPORTES_UBICAR_DOCUMENTO => array("ID" => TABMENUITEM_REPORTES_UBICAR_DOCUMENTO, "NOMBRE" => "Ubicar Documento", "URL" => "acciones/reportes/tesoreria/reportesTesoreria.php?accion=UbicarDocumento", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS, PERFIL_ANALISTA_TESORERIA)),			
			TABMENUITEM_REPORTES_OPERACIONES_EMITIDAS => array("ID" => TABMENUITEM_REPORTES_OPERACIONES_EMITIDAS, "NOMBRE" => "Operaciones emitidas", "URL" => "acciones/reportes/tesoreria/reportesTesoreria.php?accion=OperacionesEmitidas", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS, PERFIL_ANALISTA_TESORERIA)),				
			TABMENUITEM_REPORTES_SALDOS_CORRECTOS => array("ID" => TABMENUITEM_REPORTES_SALDOS_CORRECTOS, "NOMBRE" => "Saldos correctos", "URL" => "acciones/reportes/tesoreria/reportesTesoreria.php?accion=SaldosCorrectos", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD,PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS, PERFIL_ANALISTA_TESORERIA)),				
			TABMENUITEM_REPORTES_RELACION_CONTABILIDAD => array("ID" => TABMENUITEM_REPORTES_RELACION_CONTABILIDAD, "NOMBRE" => "Relaci&oacute;n Contabilidad", "URL" => "acciones/reportes/tesoreria/reportesTesoreria.php?accion=RelacionContabilidad", "PERFILES" => array(PERFIL_TESORERO,PERFIL_JEFE_FINANZAS, PERFIL_ANALISTA_TESORERIA, PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_ANALISTA_CONTABLE))			
			),
		TABMENU_TESORERIA_CONCILIACION_BANCARIA => 
		array(
			TABMENUITEM_CONCILIACION_BANCARIA_CONCILIAR => array("ID" => TABMENUITEM_CONCILIACION_BANCARIA_CONCILIAR, "NOMBRE" => "Conciliar", "URL" => "procesos/tesoreria/conciliacion/conciliar.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD)),
			TABMENUITEM_CONCILIACION_BANCARIA_ANULAR => array("ID" => TABMENUITEM_CONCILIACION_BANCARIA_ANULAR, "NOMBRE" => "Anular", "URL" => "procesos/tesoreria/conciliacion/anular.php", "PERFILES" => array(PERFIL_ANALISTA_CONTABLE,PERFIL_COORDINADOR_CONTABILIDAD))
			),
		TABMENU_COMPRAS_REQUISICION => 
		array(
			TABMENUITEM_REQUISICION_BANDEJA => array("ID" => TABMENUITEM_REQUISICION_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos/rqui/bandeja.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ASISTENTE_PRESIDENCIA,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS)),
			TABMENUITEM_REQUISICION_BUSQUEDA => array("ID" => TABMENUITEM_REQUISICION_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "documentos/rqui/busquedas.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ASISTENTE_PRESIDENCIA,PERFIL_GERENTE,PERFIL_DIRECTOR,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS)),
			TABMENUITEM_REQUISICION_INSERTAR => array("ID" => TABMENUITEM_REQUISICION_INSERTAR, "NOMBRE" => "Registrar", "URL" => "documentos/rqui/requisicion.php", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO,PERFIL_ASISTENTE_EJECUTIVO,PERFIL_ASISTENTE_PRESIDENCIA)),
			TABMENUITEM_REQUISICION_ESTADIA => array("ID" => TABMENUITEM_REQUISICION_ESTADIA, "NOMBRE" => "Estad&iacute;a", "URL" => "documentos/rqui/estadiaRequisiciones.php", "PERFILES" => array())
			),
		TABMENU_COMPRAS_SOLICITUD_COTIZACION => 
		array(
			TABMENUITEM_SOLICITUD_COTIZACION_BUSQUEDA => array("ID" => TABMENUITEM_SOLICITUD_COTIZACION_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "documentos/rqui/busquedas.php?tipoBusq=".TIPO_BUSQUEDA_COTIZACIONES, "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS))
			),
		TABMENU_COMPRAS_ORDEN_COMPRA => 
		array(
			TABMENUITEM_ORDEN_COMPRA_BANDEJA => array("ID" => TABMENUITEM_ORDEN_COMPRA_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "documentos/ordc/bandeja.php", "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			TABMENUITEM_ORDEN_COMPRA_BUSQUEDA => array("ID" => TABMENUITEM_ORDEN_COMPRA_BUSQUEDA, "NOMBRE" => "Buscar", "URL" => "documentos/rqui/busquedas.php?tipoBusq=".TIPO_BUSQUEDA_ORDENES_DE_COMPRA, "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO)),
			TABMENUITEM_ORDEN_COMPRA_INSERTAR => array("ID" => TABMENUITEM_ORDEN_COMPRA_INSERTAR, "NOMBRE" => "Registrar", "URL" => "documentos/ordc/ordenDeCompra.php", "PERFILES" => array(PERFIL_ANALISTA_COMPRAS)),
			TABMENUITEM_ORDEN_COMPRA_ESTADIA => array("ID" => TABMENUITEM_ORDEN_COMPRA_ESTADIA, "NOMBRE" => "Estad&iacute;a", "URL" => "documentos/ordc/estadiaOrdenesDeCompra.php", "PERFILES" => array(PERFIL_COORDINADOR_ORDENACION_PAGOS,PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS,PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_DIRECTOR_PRESUPUESTO))
			),
		TABMENU_VIATICOS_RENDICIONES_VIATICOS_NACIONALES => 
		array(
		
			/**** Bandeja de viáticos nacionales *****/
			TABMENUITEM_VIATICOS_NACIONALES_BANDEJA =>
				array(
					"ID" => TABMENUITEM_VIATICOS_NACIONALES_BANDEJA,
					"NOMBRE" => "Bandeja",
					"URL" => "acciones/vina/viaticonacional.php?accion=Bandeja", 
					"PERFILES" =>
						array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_DIRECTOR,
							PERFIL_GERENTE,
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_PRESIDENTE
						)
				),
				
			/**** Insertar viáticos nacionales *****/
			TABMENUITEM_VIATICOS_NACIONALES_INSERTAR =>  
				array(
					"ID" => TABMENUITEM_VIATICOS_NACIONALES_INSERTAR, 
					"NOMBRE" => "Registrar", 
					"URL" => "acciones/vina/viaticonacional.php?accion=Agregar", 
					"PERFILES" =>
					array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA
					)
				),
				
			/**** Búsqueda de viáticos nacionales *****/
			TABMENUITEM_VIATICOS_NACIONALES_BUSQUEDA =>
				array(	
					"ID" => TABMENUITEM_VIATICOS_NACIONALES_BUSQUEDA,
					"NOMBRE" => "Buscar",
					"URL" => "acciones/vina/viaticonacional.php?accion=Buscar",
					"PERFILES" => array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_ANALISTA_COMPRAS,
						PERFIL_ANALISTA_CONTABLE,
						PERFIL_ANALISTA_ORDENACION_PAGOS,
						PERFIL_JEFE_ORDENACION_CONTABILIDAD,						
						PERFIL_ANALISTA_PRESUPUESTO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA,
						PERFIL_COORDINADOR,
						PERFIL_COORDINADOR_COMPRAS,
						PERFIL_COORDINADOR_ORDENACION_PAGOS,
						PERFIL_DIRECTOR,
						PERFIL_DIRECTOR_EJECUTIVO,
						PERFIL_DIRECTOR_PRESUPUESTO,
						PERFIL_GERENTE,
						PERFIL_JEFE_PRESUPUESTO,
						PERFIL_PRESIDENTE
					)
				),
			
			/**** Reporte 1 *****/
			TABMENUITEM_VIATICOS_NACIONALES_REPORTE_1 =>
				array(	
					"ID" => TABMENUITEM_VIATICOS_NACIONALES_REPORTE_1,
					"NOMBRE" => "B&uacute;squeda detallada",
					"URL" => "acciones/vina/viaticonacional.php?accion=Reporte1",
					"PERFILES" => array(
						PERFIL_COORDINADOR_ORDENACION_PAGOS,
						PERFIL_ANALISTA_ORDENACION_PAGOS,
						PERFIL_JEFE_ORDENACION_CONTABILIDAD,
						PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS
						
					)
				),
			TABMENUITEM_VIATICOS_NACIONALES_REPORTE_RESPONSABLES =>
				array(
					"ID" => TABMENUITEM_VIATICOS_NACIONALES_REPORTE_RESPONSABLES,
					"NOMBRE" => "Historial vi&aacute;tico",
					"URL" => "acciones/vina/viaticonacional.php?accion=ReporteResponsables",
					"PERFILES" => array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_ANALISTA_CONTABLE,
						PERFIL_ANALISTA_ORDENACION_PAGOS,
						PERFIL_JEFE_ORDENACION_CONTABILIDAD,
						PERFIL_ANALISTA_PRESUPUESTO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA,
						PERFIL_COORDINADOR,
						PERFIL_COORDINADOR_ORDENACION_PAGOS,
						PERFIL_DIRECTOR,
						PERFIL_DIRECTOR_EJECUTIVO,
						PERFIL_DIRECTOR_PRESUPUESTO,
						PERFIL_GERENTE,
						PERFIL_JEFE_PRESUPUESTO,
						PERFIL_PRESIDENTE
					)
				)
			),
		TABMENU_VIATICOS_RENDICIONES_AVANCES => 
			array(
				/***** Bandeja de avances *****/
				TABMENUITEM_AVANCES_BANDEJA =>
					array(
						"ID" => TABMENUITEM_AVANCES_BANDEJA,
						"NOMBRE" => "Bandeja",
						"URL" => "acciones/avan/avance.php?accion=Bandeja",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_DIRECTOR,
							PERFIL_GERENTE,
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_PRESIDENTE
						)
					),
				/***** Insertar avances *****/
				TABMENUITEM_AVANCES_INSERTAR =>
					array(
						"ID" => TABMENUITEM_AVANCES_INSERTAR,
						"NOMBRE" => "Registrar",
						"URL" => "acciones/avan/avance.php?accion=Insertar",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA
						)
					),
				/***** Búsqueda de avances *****/
				TABMENUITEM_AVANCES_BUSQUEDA =>
					array(
						"ID" => TABMENUITEM_AVANCES_BUSQUEDA,
						"NOMBRE" => "Buscar",
						"URL" => "acciones/avan/avance.php?accion=Buscar",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ANALISTA_CONTABLE,
							PERFIL_ANALISTA_ORDENACION_PAGOS,
							PERFIL_JEFE_ORDENACION_CONTABILIDAD,							
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_COORDINADOR,
							PERFIL_COORDINADOR_ORDENACION_PAGOS,
							PERFIL_DIRECTOR,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_DIRECTOR_PRESUPUESTO,
							PERFIL_GERENTE,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_PRESIDENTE
						)
					),
				TABMENUITEM_AVANCES_REPORTE_RESPONSABLES =>
					array(
						"ID" => TABMENUITEM_AVANCES_REPORTE_RESPONSABLES,
						"NOMBRE" => "Historial avance",
						"URL" => "acciones/avan/avance.php?accion=ReporteResponsables",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ANALISTA_CONTABLE,
							PERFIL_ANALISTA_ORDENACION_PAGOS,
							PERFIL_JEFE_ORDENACION_CONTABILIDAD,
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_COORDINADOR,
							PERFIL_COORDINADOR_ORDENACION_PAGOS,
							PERFIL_DIRECTOR,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_DIRECTOR_PRESUPUESTO,
							PERFIL_GERENTE,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_PRESIDENTE
						)
					)
					//,
				/***** Archivos de pagos de avances *****/
				/*TABMENUITEM_AVANCES_ARCHIVOS_PAGOS =>
					array(
						"ID" => TABMENUITEM_AVANCES_ARCHIVOS_PAGOS,
						"NOMBRE" => "Archivos de pagos",
						"URL" => "acciones/avan/avance.php?accion=ArchivosPagos",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA
						)
					)*/
				),
		TABMENU_VIATICOS_RENDICIONES_RENDICIONES_AVANCES => 
			array(
				TABMENUITEM_RENDICIONES_AVANCES_BANDEJA =>
					array(
						"ID" => TABMENUITEM_RENDICIONES_AVANCES_BANDEJA,
						"NOMBRE" => "Bandeja",
						"URL" => "acciones/avan/rendicion.php?accion=Bandeja",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_DIRECTOR,
							PERFIL_GERENTE,
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_PRESIDENTE
						)
					),
				TABMENUITEM_RENDICIONES_AVANCES_INSERTAR =>
					array(
						"ID" => TABMENUITEM_RENDICIONES_AVANCES_INSERTAR,
						"NOMBRE" => "Registrar",
						"URL" => "acciones/avan/rendicion.php?accion=Insertar",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA
						)
					),
				TABMENUITEM_RENDICIONES_AVANCES_BUSQUEDA =>
					array(
						"ID" => TABMENUITEM_RENDICIONES_AVANCES_BUSQUEDA,
						"NOMBRE" => "Buscar",
						"URL" => "acciones/avan/rendicion.php?accion=BuscarRendicion",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_ANALISTA_CONTABLE,
							PERFIL_ANALISTA_ORDENACION_PAGOS,
							PERFIL_JEFE_ORDENACION_CONTABILIDAD,							
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_COORDINADOR,
							PERFIL_COORDINADOR_ORDENACION_PAGOS,
							PERFIL_DIRECTOR,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_DIRECTOR_PRESUPUESTO,
							PERFIL_GERENTE,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_PRESIDENTE
						)
					)
				),
		TABMENU_VIATICOS_RENDICIONES_RENDICIONES => 
		array(
			TABMENUITEM_RENDICIONES_BANDEJA =>
				array(
					"ID" => TABMENUITEM_RENDICIONES_BANDEJA,
					"NOMBRE" => "Bandeja",
					"URL" => "acciones/vina/rendicion.php?accion=bandeja",
					"PERFILES" => array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_DIRECTOR,
						PERFIL_GERENTE,
						PERFIL_ANALISTA_PRESUPUESTO,
						PERFIL_JEFE_PRESUPUESTO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_DIRECTOR_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA,
						PERFIL_PRESIDENTE
					)
				),
			TABMENUITEM_RENDICIONES_INSERTAR =>
				array(
					"ID" => TABMENUITEM_RENDICIONES_INSERTAR,
					"NOMBRE" => "Registrar",
					"URL" => "acciones/vina/rendicion.php?accion=Insertar",
					"PERFILES" => array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA
					)
				),
			TABMENUITEM_RENDICIONES_BUSQUEDA =>
				array(
					"ID" => TABMENUITEM_RENDICIONES_BUSQUEDA,
					"NOMBRE" => "Buscar",
					"URL" => "acciones/vina/rendicion.php?accion=BuscarRendicion",
					"PERFILES" => array(
						PERFIL_ASISTENTE_ADMINISTRATIVO,
						PERFIL_ANALISTA_CONTABLE,
						PERFIL_ANALISTA_ORDENACION_PAGOS,
						PERFIL_JEFE_ORDENACION_CONTABILIDAD,						
						PERFIL_ANALISTA_PRESUPUESTO,
						PERFIL_ASISTENTE_EJECUTIVO,
						PERFIL_ASISTENTE_PRESIDENCIA,
						PERFIL_COORDINADOR,
						PERFIL_COORDINADOR_ORDENACION_PAGOS,
						PERFIL_DIRECTOR,
						PERFIL_DIRECTOR_EJECUTIVO,
						PERFIL_DIRECTOR_PRESUPUESTO,
						PERFIL_GERENTE,
						PERFIL_JEFE_PRESUPUESTO,
						PERFIL_PRESIDENTE
					)
				)
			),
		TABMENU_VIATICOS_RENDICIONES_VIATICOS_INTERNACIONALES => 
		array(
			TABMENUITEM_VIATICOS_INTERNACIONALES_BANDEJA => array("ID" => TABMENUITEM_VIATICOS_INTERNACIONALES_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "#", "PERFILES" => array()),
			TABMENUITEM_VIATICOS_INTERNACIONALES_INSERTAR => array("ID" => TABMENUITEM_VIATICOS_INTERNACIONALES_INSERTAR, "NOMBRE" => "Insertar", "URL" => "#", "PERFILES" => array()),
			TABMENUITEM_VIATICOS_INTERNACIONALES_BUSQUEDA => array("ID" => TABMENUITEM_VIATICOS_INTERNACIONALES_BUSQUEDA, "NOMBRE" => "B&uacute;squeda", "URL" => "#", "PERFILES" => array())
			),
		TABMENU_MEMO =>
		array(
			  TABMENUITEM_MEMO => array("ID" => TABMENUITEM_MEMO, "NOMBRE" => Memos, "URL" => "procesos/memo/formato.html","PERFILES" => array())
		      ),
		TABMENU_COMUNICACIONES_MEMORANDOS => 
		array(
			TABMENUITEM_COMUNICACIONES_MEMORANDOS_BANDEJA => array("ID" => TABMENUITEM_COMUNICACIONES_MEMORANDOS_BANDEJA, "NOMBRE" => "B&uacute;squeda", "URL" => "documentos/memo/buscar.php?tipo=memo&bandeja=1", "PERFILES" => array()),
			TABMENUITEM_COMUNICACIONES_MEMORANDOS_INSERTAR => array("ID" => TABMENUITEM_COMUNICACIONES_MEMORANDOS_INSERTAR, "NOMBRE" => "Ingresar memorando", "URL" => "documentos/memo/ingresar.php?tipo=memo", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO, PERFIL_ASISTENTE_EJECUTIVO, PERFIL_ASISTENTE_PRESIDENCIA, PERFIL_TESORERO, PERFIL_JEFE, PERFIL_GERENTE, PERFIL_DIRECTOR, PERFIL_DIRECTOR_EJECUTIVO, PERFIL_PRESIDENTE))
			),
		TABMENU_COMUNICACIONES_OFICIOS => 
		array(
			TABMENUITEM_COMUNICACIONES_OFICIOS_BANDEJA => array("ID" => TABMENUITEM_COMUNICACIONES_OFICIOS_BANDEJA, "NOMBRE" => "B&uacute;squeda", "URL" => "documentos/memo/buscar.php?tipo=ofic&bandeja=1", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO, PERFIL_ASISTENTE_EJECUTIVO, PERFIL_ASISTENTE_PRESIDENCIA, PERFIL_JEFE, PERFIL_GERENTE, PERFIL_DIRECTOR, PERFIL_DIRECTOR_EJECUTIVO, PERFIL_PRESIDENTE)),
			TABMENUITEM_COMUNICACIONES_OFICIOS_INSERTAR => array("ID" => TABMENUITEM_COMUNICACIONES_OFICIOS_INSERTAR, "NOMBRE" => "Ingresar oficio", "URL" => "documentos/memo/ingresar.php?tipo=ofic", "PERFILES" => array(PERFIL_ASISTENTE_ADMINISTRATIVO, PERFIL_ASISTENTE_EJECUTIVO, PERFIL_ASISTENTE_PRESIDENCIA, PERFIL_JEFE, PERFIL_GERENTE, PERFIL_DIRECTOR, PERFIL_DIRECTOR_EJECUTIVO, PERFIL_PRESIDENTE))
			),
		TABMENU_BUSQUEDA => 
		array(
			TABMENUITEM_BUSQUEDA_UBICAR_DOCUMENTO => array("ID" => TABMENUITEM_BUSQUEDA_UBICAR_DOCUMENTO, "NOMBRE" => "Ubicar documento", "URL" => "#", "PERFILES" => array())
			),
		TABMENU_RECURSOS_EMPLEADO => 
		array(
			TABMENUITEM_EMPLEADO_GESTIONAR_EMPLEADO => array("ID" => TABMENUITEM_EMPLEADO_GESTIONAR_EMPLEADO, "NOMBRE" => "Ingresar empleado FI", "URL" => "recursos/empleado/ingresarEmpleado.php", "PERFILES" => array(PERFIL_ADMINISTRADOR, PERFIL_JEFE_PERSONAL, PERFIL_ESPECIALISTA_PERSONAL, PERFIL_ANALISTA_I_TALENTO_HUMANO)),
			TABMENUITEM_EMPLEADO_BUSCAR_EMPLEADOS => array("ID" => TABMENUITEM_EMPLEADO_BUSCAR_EMPLEADOS, "NOMBRE" => "Buscar empleados FI", "URL" => "recursos/empleado/buscarEmpleado.php", "PERFILES" => array(PERFIL_ADMINISTRADOR, PERFIL_JEFE_PERSONAL, PERFIL_ESPECIALISTA_PERSONAL, PERFIL_ANALISTA_I_TALENTO_HUMANO)),
			TABMENUITEM_EMPLEADO_GESTIONAR_OTROS_TRABAJADORES => array("ID" => TABMENUITEM_EMPLEADO_GESTIONAR_OTROS_TRABAJADORES, "NOMBRE" => "Ingresar otros trabajadores", "URL" => "recursos/empleado/ingresarTrabajador.php", "PERFILES" => array(PERFIL_ADMINISTRADOR, PERFIL_JEFE_PERSONAL, PERFIL_ESPECIALISTA_PERSONAL,PERFIL_ASISTENTE_ADMINISTRATIVO_EDUCACION, PERFIL_ANALISTA_I_TALENTO_HUMANO, PERFIL_ASISTENTE_ADMINISTRATIVO_REDES)),
			TABMENUITEM_EMPLEADO_BUSCAR_OTROS_TRABAJADORES => array("ID" => TABMENUITEM_EMPLEADO_BUSCAR_OTROS_TRABAJADORES, "NOMBRE" => "Buscar otros trabajadores", "URL" => "recursos/empleado/buscarTrabajador.php", "PERFILES" => array(PERFIL_ADMINISTRADOR, PERFIL_JEFE_PERSONAL, PERFIL_ESPECIALISTA_PERSONAL,PERFIL_ASISTENTE_ADMINISTRATIVO_EDUCACION, PERFIL_ANALISTA_I_TALENTO_HUMANO, PERFIL_ASISTENTE_ADMINISTRATIVO_REDES))
			),
		TABMENU_RECURSOS_USUARIO => 
		array(
			TABMENUITEM_USUARIO_GESTIONAR => array("ID" => TABMENUITEM_USUARIO_GESTIONAR, "NOMBRE" => "Ingresar usuario", "URL" => "recursos/usuario/ingresar.php", "PERFILES" => array(PERFIL_ADMINISTRADOR)),
			TABMENUITEM_USUARIO_BUSCAR => array("ID" => TABMENUITEM_USUARIO_BUSCAR, "NOMBRE" => "Buscar usuario", "URL" => "recursos/usuario/buscar.php", "PERFILES" => array(PERFIL_ADMINISTRADOR)),
			TABMENUITEM_USUARIO_CONTRASENA => array("ID" => TABMENUITEM_USUARIO_CONTRASENA, "NOMBRE" => "Cambiar contrase&ntilde;a", "URL" => "recursos/usuario/modificar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES, PERFIL_ANALISTA_COMPRAS, PERFIL_ANALISTA_CONTABLE, PERFIL_ANALISTA_ORDENACION_PAGOS, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ANALISTA_TESORERIA, PERFIL_ASISTENTE_ADMINISTRATIVO, PERFIL_ASISTENTE_EJECUTIVO, PERFIL_ASISTENTE_PRESUPUESTO, PERFIL_ASISTENTE_PRESIDENCIA, PERFIL_COORDINADOR_BIENES, PERFIL_COORDINADOR_COMPRAS, PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_COORDINADOR_ORDENACION_PAGOS, PERFIL_DIRECTOR, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS, PERFIL_DIRECTOR_EJECUTIVO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ESPECIALISTA_PERSONAL, PERFIL_GERENTE, PERFIL_JEFE_BIENES, PERFIL_JEFE_FINANZAS, PERFIL_JEFE_ORDENACION_CONTABILIDAD, PERFIL_JEFE_PRESUPUESTO, PERFIL_PRESIDENTE, PERFIL_TESORERO
			))			
			),
		TABMENU_RECURSOS_CARGO => 
		array(
			TABMENUITEM_CARGO_GESTIONAR => array("ID" => TABMENUITEM_CARGO_GESTIONAR, "NOMBRE" => "Asociar cargo a dependencia", "URL" => "recursos/cargo/ingresar.php", "PERFILES" => array(PERFIL_ADMINISTRADOR,PERFIL_ESPECIALISTA_PERSONAL)),
			TABMENUITEM_CARGO_BUSCAR => array("ID" => TABMENUITEM_CARGO_BUSCAR, "NOMBRE" => "Administrar cargos y dependencias", "URL" => "recursos/cargo/buscar.php", "PERFILES" => array(PERFIL_ADMINISTRADOR,PERFIL_ESPECIALISTA_PERSONAL))
			),			
		TABMENU_RECURSOS_BANCOS => 
		array(
			TABMENUITEM_BANCOS_GESTIONAR => array("ID" => TABMENUITEM_BANCOS_GESTIONAR, "NOMBRE" => "Registrar", "URL" => "recursos/banco/ingresar.php", "PERFILES" => array(PERFIL_TESORERO,PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_BANCOS_BUSCAR => array("ID" => TABMENUITEM_BANCOS_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/banco/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS))
			),
		TABMENU_RECURSOS_CUENTAS_BANCARIAS => 
		array(
			TABMENUITEM_CUENTAS_BANCARIAS_GESTIONAR => array("ID" => TABMENUITEM_CUENTAS_BANCARIAS_GESTIONAR, "NOMBRE" => "Registrar", "URL" => "recursos/banco/cuentaBancaria/ingresarCuenta.php", "PERFILES" => array(PERFIL_TESORERO,PERFIL_JEFE_FINANZAS)),
			TABMENUITEM_CUENTAS_BANCARIAS_BUSCAR => array("ID" => TABMENUITEM_CUENTAS_BANCARIAS_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/banco/cuentaBancaria/buscarCuenta.php", "PERFILES" => array(PERFIL_ANALISTA_TESORERIA,PERFIL_TESORERO,PERFIL_JEFE_FINANZAS))
			),
		TABMENU_RECURSOS_PROVEEDORES => 
		array(
			TABMENUITEM_PROVEEDORES_GESTIONAR => array("ID" => TABMENUITEM_PROVEEDORES_GESTIONAR, "NOMBRE" => "Ingresar proveedor", "URL" => "recursos/proveedor/ingresar.php", "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS)),
			TABMENUITEM_PROVEEDORES_BUSCAR => array("ID" => TABMENUITEM_PROVEEDORES_BUSCAR, "NOMBRE" => "Buscar proveedor", "URL" => "recursos/proveedor/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS)),
			TABMENUITEM_PROVEEDORES_REPORTES => array("ID" => TABMENUITEM_PROVEEDORES_REPORTES, "NOMBRE" => "Reportes", "URL" => "recursos/proveedor/reportes.php", "PERFILES" => array(PERFIL_ANALISTA_COMPRAS,PERFIL_COORDINADOR_COMPRAS))
			),
		TABMENU_RECURSOS_SERVICIOS => 
		array(
			TABMENUITEM_SERVICIOS_INSERTAR => array("ID" => TABMENUITEM_SERVICIOS_INSERTAR, "NOMBRE" => "Ingresar servicio", "URL" => "recursos/servicio/ingresarServicio.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),
			TABMENUITEM_SERVICIOS_BUSCAR => array("ID" => TABMENUITEM_SERVICIOS_BUSCAR, "NOMBRE" => "Buscar servicio", "URL" => "recursos/servicio/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ANALISTA_PRESUPUESTO,PERFIL_JEFE_PRESUPUESTO, PERFIL_ANALISTA_I_PASANTE_BIENES))
			),			
		TABMENU_RECURSOS_PARTIDAS_PRESUPUESTARIAS => 
		array(
			TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_INSERTAR => array("ID" => TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_INSERTAR, "NOMBRE" => "Ingresar partida presupuestaria", "URL" => "recursos/presupuesto/partidas/ingresar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO)),
			TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BUSCAR => array("ID" => TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BUSCAR, "NOMBRE" => "Buscar partida presupuestaria", "URL" => "recursos/presupuesto/partidas/buscar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ASISTENTE_PRESUPUESTO)),
			TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BIENES => array("ID" => TABMENUITEM_PARTIDAS_PRESUPUESTARIAS_BIENES, "NOMBRE" => "Materiales/Activos/Servicios", "URL" => "recursos/presupuesto/partidas/materiales_activos_servicios.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ASISTENTE_PRESUPUESTO))
			),
		TABMENU_RECURSOS_CATEGORIA_PROGRAMATICA => 
		array(
			TABMENUITEM_CATEGORIA_PROGRAMATICA_INSERTAR => array("ID" => TABMENUITEM_CATEGORIA_PROGRAMATICA_INSERTAR, "NOMBRE" => "Ingresar categor&iacute;a program&aacute;tica", "URL" => "recursos/presupuesto/proyecto/ingresar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO)),
			TABMENUITEM_CATEGORIA_PROGRAMATICA_BUSCAR => array("ID" => TABMENUITEM_CATEGORIA_PROGRAMATICA_BUSCAR, "NOMBRE" => "Buscar categor&iacute;a program&aacute;tica", "URL" => "recursos/presupuesto/proyecto/buscar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ASISTENTE_PRESUPUESTO))
			),
		TABMENU_RECURSOS_ASIGNACION_PRESUPUESTO => 
		array(
			//TABMENUITEM_ASIGNACION_PRESUPUESTO_BANDEJA => array("ID" => TABMENUITEM_ASIGNACION_PRESUPUESTO_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "#", "PERFILES" => array(PERFIL_ANALISTA_PRESUPUESTO)),
			TABMENUITEM_ASIGNACION_PRESUPUESTO_INSERTAR => array("ID" => TABMENUITEM_ASIGNACION_PRESUPUESTO_INSERTAR, "NOMBRE" => "Ingresar asignaci&oacute;n presupuestaria", "URL" => "procesos/presupuesto/asignacion/ingresar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO)),
			TABMENUITEM_ASIGNACION_PRESUPUESTO_BUSCAR => array("ID" => TABMENUITEM_ASIGNACION_PRESUPUESTO_BUSCAR, "NOMBRE" => "Buscar asignaci&oacute;n presupuestaria", "URL" => "procesos/presupuesto/asignacion/buscar.php", "PERFILES" => array(PERFIL_JEFE_PRESUPUESTO, PERFIL_DIRECTOR_PRESUPUESTO, PERFIL_ANALISTA_PRESUPUESTO))
			),
		TABMENU_RECURSOS_ACTIVOS_CATEGORIA =>	
		array(
			TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_INGRESAR => array("ID" => TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_INGRESAR, "NOMBRE" => "Registrar","URL"=> "recursos/bienes/categoria/registrar_categoria.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),
		    TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_BUSCAR => array("ID" => TABMENUITEM_MANEJO_CATEGORIA_ACTIVOS_BUSCAR, "NOMBRE" => "Buscar","URL"=> "recursos/bienes/categoria/buscar_categoria.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES, PERFIL_ANALISTA_I_PASANTE_BIENES))
		 	),
		TABMENU_RECURSOS_ACTIVOS_MARCA =>
		array(		
		 	TABMENUITEM_MANEJO_MARCA_INGRESAR => array("ID" => TABMENUITEM_MANEJO_MARCA_INGRESAR, "NOMBRE" => "Registrar","URL"=> "recursos/bienes/marca/marca_1.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA)),
			TABMENUITEM_MANEJO_MARCA_BUSCAR => array("ID" => TABMENUITEM_MANEJO_MARCA_BUSCAR, "NOMBRE" => "Buscar","URL"=> "recursos/bienes/marca/buscar_marca.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA, PERFIL_ANALISTA_I_PASANTE_BIENES)) 
		),
		TABMENU_RECURSOS_MATERIALES_CATEGORIA =>	
		array(
			TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_INGRESAR=> array("ID" => TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_INGRESAR, "NOMBRE" => "Registrar","URL"=> "recursos/almacen/categoria/registrar_categoria.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),
		    TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_BUSCAR => array("ID" => TABMENUITEM_MANEJO_CATEGORIA_MATERIALES_BUSCAR, "NOMBRE" => "Buscar","URL"=> "recursos/almacen/categoria/buscar_categoria.php","PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES, PERFIL_ANALISTA_I_PASANTE_BIENES))
			),
		TABMENU_RECURSOS_MANEJO_INVENTARIO_REPORTES => 
		array(
			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_INVENTARIO_ACTUALIZADO => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_INVENTARIO_ACTUALIZADO, "NOMBRE" => "Inventario", "URL" => "recursos/almacen/inventario/reportes/inventario_actualizado.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_ALMACENISTA,PERFIL_DIRECTOR_EJECUTIVO, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_ARTICULO => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_ARTICULO, "NOMBRE" => "Control Interno", "URL" => "recursos/almacen/inventario/reportes/movimiento_articulo.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_FECHA => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_MOVIMIENTOS_FECHA, "NOMBRE" => "Movimientos", "URL" => "recursos/almacen/inventario/reportes/movimiento_fecha.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_GASTOS => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_GASTOS, "NOMBRE" => "Gastos", "URL" => "recursos/almacen/inventario/reportes/gastos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_COMPRAS_CONSUMO => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_COMPRAS_CONSUMO, "NOMBRE" => "Compras y consumo", "URL" => "recursos/almacen/inventario/reportes/compras_consumo.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO, PERFIL_ANALISTA_I_PASANTE_BIENES))
			),
		TABMENU_RECURSOS_MANEJO_BIENES =>
		array(
			  TABMENUITEM_MANEJO_BIEN_INGRESAR => array ("ID" => TABMENUITEM_MANEJO_BIEN_INGRESAR, "NOMBRE" => "Registrar", "URL" => "recursos/bienes/activo/bien_1.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA)),
			  TABMENUITEM_MANEJO_BIEN_BUSCAR => array ("ID" => TABMENUITEM_MANEJO_BIEN_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/bienes/activo/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA,PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ANALISTA_I_PASANTE_BIENES))
			  ),
		
		TABMENU_RECURSOS_ACCIONES_BIEN =>
		array(
		    TABMENUITEM_ACCIONES_BANDEJA_BIEN => array("ID" => TABMENUITEM_ACCIONES_BANDEJA_BIEN, "NOMBRE" => "Bandeja", "URL" => "recursos/bienes/bandeja.php", "PERFILES" => array(PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ANALISTA_BIENES,PERFIL_ALMACENISTA)),
		    TABMENUITEM_ACCIONES_INCORPORAR_BIEN => array("ID" => TABMENUITEM_ACCIONES_INCORPORAR_BIEN, "NOMBRE" => "Entrada", "URL" => "recursos/bienes/incorporar_activos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA)),
	        TABMENUITEM_ACCIONES_SALIDAS_BIEN => array("ID" => TABMENUITEM_ACCIONES_SALIDAS_BIEN, "NOMBRE" => "Salida","URL" => "recursos/bienes/salida_activos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA)),
   			TABMENUITEM_MANEJO_INVENTARIO_REPORTES_ACTAS => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_ACTAS, "NOMBRE" => "Buscar", "URL" => "recursos/bienes/reportes/actas.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ALMACENISTA,PERFIL_ANALISTA_I_TECNOLOGIA,PERFIL_ANALISTA_II_TECNOLOGIA,PERFIL_GERENTE_TECNOLOGIA,PERFIL_JEFE_SEG_Y_CONTROL, PERFIL_ANALISTA_I_PASANTE_BIENES))
		),
		
		TABMENU_RECURSOS_CUSTODIA_BIEN =>
		array(
	         TABMENUITEM_CUSTODIA_BIEN => array("ID" => TABMENUITEM_CUSTODIA_BIEN, "NOMBRE" => "Registrar", "URL" => "recursos/bienes/cambio_custodia.php","PERFILES" =>array(PERFIL_ALMACENISTA,PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES))		
		),
		
		TABMENU_RECURSOS_REASIGNACION_BIEN =>
		array(
	         TABMENUITEM_RECURSOS_REASIGNACION_BIEN => array("ID" => TABMENUITEM_RECURSOS_REASIGNACION_BIEN, "NOMBRE" => "Re-asignar", "URL" => "recursos/bienes/reasignar_activos.php","PERFILES" =>array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),
	         TABMENUITEM_RECURSOS_REASIGNACION_BIEN_BUSCAR => array("ID" => TABMENUITEM_RECURSOS_REASIGNACION_BIEN_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/bienes/buscar_actas_reasignacion.php","PERFILES" =>array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES, PERFIL_ANALISTA_I_PASANTE_BIENES))		
		),
			 
		TABMENU_RECURSOS_GARANTIA_BIEN =>
		array(
		TABMENUITEM_BIENES_REPORTES_GARANTIA=> array("ID" => TABMENUITEM_BIENES_REPORTES_GARANTIA,"NOMBRE" => "Reportar", "URL" => "recursos/bienes/garantia/garantia_activos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ALMACENISTA)),    
		TABMENUITEM_GARANTIA_BIEN => array("ID" => TABMENUITEM_GARANTIA_BIEN, "NOMBRE" => "Bandeja", "URL" => "recursos/bienes/garantia/bandeja.php","PERFILES" =>array(PERFIL_ANALISTA_BIENES)),
		TABMENUITEM_GARANTIA_BIEN_BUSCAR => array ("ID" => TABMENUITEM_GARANTIA_BIEN_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/bienes/garantia/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES, PERFIL_ANALISTA_I_PASANTE_BIENES))	
		),
		
		TABMENU_RECURSOS_DESINCORPORACION_BIEN =>
			array(
				TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BANDEJA =>
					array(
						"ID" => TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BANDEJA,
						"NOMBRE" => "Bandeja",
						"URL" => "acciones/bienes/desincorporacion.php?accion=Bandeja",
						"PERFILES" =>
							array(
								PERFIL_ANALISTA_BIENES,
								PERFIL_JEFE_BIENES,
								PERFIL_COORDINADOR_BIENES,
								PERFIL_ALMACENISTA
							)
					),
					    
				TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_REGISTRAR =>
					array(
						"ID" => TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_REGISTRAR,
						"NOMBRE" => "Registrar",
						"URL" => "acciones/bienes/desincorporacion.php?accion=Registrar",
						"PERFILES" =>
							array(
								PERFIL_ANALISTA_BIENES,
								PERFIL_JEFE_BIENES,
								PERFIL_COORDINADOR_BIENES,
								PERFIL_ALMACENISTA
							)
					),
					
				TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BUSCAR =>
					array(
						"ID" => TABMENUITEM_RECURSOS_DESINCORPORACION_BIEN_BUSCAR,
						"NOMBRE" => "Buscar",
						"URL" => "acciones/bienes/desincorporacion.php?accion=Buscar",
						"PERFILES" =>
							array(
								PERFIL_ANALISTA_BIENES,
								PERFIL_JEFE_BIENES,
								PERFIL_COORDINADOR_BIENES,
								PERFIL_ALMACENISTA
							)
					)
		),
		
		TABMENU_RECURSOS_BIENES_REPORTES => 
		array(
			TABMENUITEM_BIENES_REPORTES_INVENTARIO_ACTIVOS => array("ID" => TABMENUITEM_BIENES_REPORTES_INVENTARIO_ACTIVOS, "NOMBRE" => "Inventario", "URL" => "recursos/bienes/reportes/inventario_activos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_ALMACENISTA,PERFIL_ANALISTA_I_TECNOLOGIA,PERFIL_ANALISTA_II_TECNOLOGIA,PERFIL_GERENTE_TECNOLOGIA,PERFIL_JEFE_SEG_Y_CONTROL, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_BIENES_REPORTES_ACTIVOS_ADQUIRIDOS => array("ID" => TABMENUITEM_BIENES_REPORTES_ACTIVOS_ADQUIRIDOS, "NOMBRE" => "Movimientos", "URL" => "recursos/bienes/reportes/movimientos.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_ALMACENISTA,PERFIL_ANALISTA_I_TECNOLOGIA,PERFIL_ANALISTA_II_TECNOLOGIA,PERFIL_GERENTE_TECNOLOGIA,PERFIL_JEFE_SEG_Y_CONTROL, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_BIENES_REPORTES_SALIDAS=> array("ID" => TABMENUITEM_BIENES_REPORTES_SALIDAS, "NOMBRE" => "Salidas", "URL" => "recursos/bienes/reportes/salidas.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ALMACENISTA,PERFIL_ANALISTA_I_TECNOLOGIA,PERFIL_ANALISTA_II_TECNOLOGIA,PERFIL_GERENTE_TECNOLOGIA,PERFIL_JEFE_SEG_Y_CONTROL, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			TABMENUITEM_BIENES_REPORTES_ENTREGA=> array("ID" => TABMENUITEM_BIENES_REPORTES_ENTREGA,"NOMBRE" => "Recepci&oacute;n", "URL" => "recursos/bienes/reportes/entregas.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_PRESIDENTE,PERFIL_ALMACENISTA,PERFIL_ANALISTA_I_TECNOLOGIA,PERFIL_ANALISTA_II_TECNOLOGIA,PERFIL_GERENTE_TECNOLOGIA,PERFIL_JEFE_SEG_Y_CONTROL, PERFIL_ANALISTA_I_PASANTE_BIENES))
			),		

		TABMENU_RECURSOS_CONTABILIDAD => 
		array(
			TABMENUITEM_CONTABILIDAD_INGRESAR_CUENTAS_CONTABLES => array("ID" => TABMENUITEM_CONTABILIDAD_INGRESAR_CUENTAS_CONTABLES, "NOMBRE" => "Ingresar Cuentas Contables", "URL" => "recursos/contabilidad/ingresarCuenta.php", "PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_COORDINADOR_CONTABILIDAD)),
			TABMENUITEM_CONTABILIDAD_BUSCAR_CUENTAS_CONTABLES => array("ID" => TABMENUITEM_CONTABILIDAD_BUSCAR_CUENTAS_CONTABLES, "NOMBRE" => "Buscar Cuentas Contables", "URL" => "recursos/contabilidad/buscarCuenta.php", "PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_ANALISTA_CONTABLE, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS)),
			TABMENUITEM_CONTABILIDAD_INGRESAR_CONVERTIDOR => array("ID" => TABMENUITEM_CONTABILIDAD_INGRESAR_CONVERTIDOR, "NOMBRE" => "Ingresar Convertidor", "URL" => "recursos/contabilidad/ingresarConvertidor.php", "PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_COORDINADOR_CONTABILIDAD)),
			TABMENUITEM_CONTABILIDAD_BUSCAR_CONVERTIDOR => array("ID" => TABMENUITEM_CONTABILIDAD_BUSCAR_CONVERTIDOR, "NOMBRE" => "Buscar Convertidor", "URL" => "recursos/contabilidad/buscarConvertidor.php", "PERFILES" => array(PERFIL_JEFE_ORDENACION_CONTABILIDAD,PERFIL_COORDINADOR_CONTABILIDAD, PERFIL_ANALISTA_CONTABLE, PERFIL_DIRECTOR_ADMINISTRACION_FINANZAS))
			),
		TABMENU_RECURSOS_VIATICOS_CATEGORIAS => 
		array(
			TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR => array("ID" => TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR, "NOMBRE" => "Gestionar categor&iacute;as", "URL" => "#", "PERFILES" => array()),
			TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR_ASIGNACIONES => array("ID" => TABMENUITEM_VIATICOS_CATEGORIAS_GESTIONAR_ASIGNACIONES, "NOMBRE" => "Gestionar asignaciones por categor&iacute;a", "URL" => "#", "PERFILES" => array()),
			TABMENUITEM_VIATICOS_CATEGORIAS_BUSCAR_CATEGORIAS => array("ID" => TABMENUITEM_VIATICOS_CATEGORIAS_BUSCAR_CATEGORIAS, "NOMBRE" => "Buscar categor&iacute;as", "URL" => "#", "PERFILES" => array())
			),
		TABMENU_RECURSOS_MANEJO_ARTICULOS =>
		array(
			  TABMENUITEM_MANEJO_ARTICULO_GESTIONAR => array("ID" => TABMENUITEM_MANEJO_ARTICULO_GESTIONAR, "NOMBRE" => "Registrar", "URL" => "recursos/almacen/articulo/ingresar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA)),
			  TABMENUITEM_MANEJO_ARTICULO_BUSCAR => array("ID" => TABMENUITEM_MANEJO_ARTICULO_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/almacen/articulo/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA,PERFIL_JEFE_PRESUPUESTO,PERFIL_ANALISTA_PRESUPUESTO, PERFIL_ANALISTA_I_PASANTE_BIENES))			  
		    ),	
		TABMENU_RECURSOS_MANEJO_INVENTARIO =>
		array(
			  TABMENUITEM_MANEJO_INVENTARIO_CARGA_BANDEJA => array ("ID" => TABMENUITEM_MANEJO_INVENTARIO_CARGA_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "recursos/almacen/inventario/materialesBandeja.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_MANEJO_INVENTARIO_CARGA => array ("ID" => TABMENUITEM_MANEJO_INVENTARIO_CARGA, "NOMBRE" => "Registrar", "URL" => "recursos/almacen/inventario/registrar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_MANEJO_INVENTARIO_DISMINUCION => array ("ID" => TABMENUITEM_MANEJO_INVENTARIO_DISMINUCION, "NOMBRE" => "Disminuir", "URL" => "recursos/almacen/inventario/disminuir.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),
			  /*TABMENUITEM_MANEJO_INVENTARIO_MODIFICACION => array ("ID" => TABMENUITEM_MANEJO_INVENTARIO_MODIFICACION, "NOMBRE" => "Modificar","URL" => "recursos/almacen/inventario/modificar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES)),*/
  			  TABMENUITEM_MANEJO_INVENTARIO_REPORTES_ACTAS => array("ID" => TABMENUITEM_MANEJO_INVENTARIO_REPORTES_ACTAS, "NOMBRE" => "Buscar", "URL" => "recursos/almacen/inventario/reportes/actas.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES, PERFIL_ANALISTA_I_PASANTE_BIENES)),
			  TABMENUITEM_MANEJO_INVENTARIO_SALIDA => array ("ID" => TABMENUITEM_MANEJO_INVENTARIO_SALIDA , "NOMBRE" => "Asignar", "URL" => "recursos/almacen/inventario/salida_activos_almacen.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES))
			),
		TABMENU_RECURSOS_RESP_SOCIAL_ADMINISTRAR =>	
		array(
			  TABMENUITEM_RESP_SOCIAL_GESTIONAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_GESTIONAR, "NOMBRE" => "Registrar", "URL" => "recursos/resp_social/ingresar_item.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_RESP_SOCIAL_BUSCAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/resp_social/buscar.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) )
				),			
		TABMENU_RECURSOS_RESP_SOCIAL_INVENTARIO =>	
		array(
			  TABMENUITEM_RESP_SOCIAL_BANDEJA => array ("ID" => TABMENUITEM_RESP_SOCIAL_BANDEJA, "NOMBRE" => "Bandeja", "URL" => "recursos/resp_social/respsocialBandeja.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_RESP_SOCIAL_INGRESAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_INGRESAR, "NOMBRE" => "Registrar", "URL" => "recursos/resp_social/registrar_inventario.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_RESP_SOCIAL_ASIGNAR=> array ("ID" => TABMENUITEM_RESP_SOCIAL_ASIGNAR, "NOMBRE" => "Asignar", "URL" => "recursos/resp_social/asignar_inventario.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_RESP_SOCIAL_BUSCAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/resp_social/reportes/buscar_actas.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) )
				)	,
		TABMENU_RECURSOS_RESP_SOCIAL_CUSTODIA =>
		array(
			  TABMENUITEM_RESP_SOCIAL_CUSTODIA => array ("ID" => TABMENUITEM_RESP_SOCIAL_CUSTODIA, "NOMBRE" => "Registrar", "URL" => "recursos/resp_social/cambio_custodia_rs.php", "PERFILES" => array(PERFIL_ALMACENISTA) )
			  ),
		TABMENU_RECURSOS_RESP_SOCIAL_REPORTES =>	  
		array(
			  TABMENUITEM_RESP_SOCIAL_REPORTES_INVENTARIO => array ("ID" => TABMENUITEM_RESP_SOCIAL_REPORTES_INVENTARIO, "NOMBRE" => "Inventario", "URL" => "recursos/resp_social/reportes/inventario_rs.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA,PERFIL_PRESIDENTE,PERFIL_DIRECTOR_EJECUTIVO,PERFIL_ALMACENISTA) )
			  )	,
		TABMENU_RECURSOS_RESP_SOCIAL_CATEGORIA =>
		array(
			  TABMENUITEM_RESP_SOCIAL_CATEGORIA_INGRESAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_CATEGORIA_INGRESAR, "NOMBRE" => "Registrar", "URL" => "recursos/resp_social/categoria/registrar_categoria.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA) ),
			  TABMENUITEM_RESP_SOCIAL_CATEGORIA_BUSCAR => array ("ID" => TABMENUITEM_RESP_SOCIAL_CATEGORIA_BUSCAR, "NOMBRE" => "Buscar", "URL" => "recursos/resp_social/categoria/buscar_categoria.php", "PERFILES" => array(PERFIL_ANALISTA_BIENES,PERFIL_JEFE_BIENES,PERFIL_COORDINADOR_BIENES,PERFIL_ALMACENISTA, PERFIL_ANALISTA_I_PASANTE_BIENES) )
			  ),
		TABMENU_CAJA_CHICA_APERTURA =>
			array(
				TABMENUITEM_CAJA_CHICA_APERTURA_INSERTAR =>
					array(
						"ID" => TABMENUITEM_CAJA_CHICA_APERTURA_INSERTAR,
						"NOMBRE" => "Registrar",
						"URL" => "acciones/cajaChica/cajaChicaApertura.php?accion=Insertar",
						"PERFILES" => array(
							PERFIL_ASISTENTE_ADMINISTRATIVO,
							PERFIL_DIRECTOR,
							PERFIL_GERENTE,
							PERFIL_ANALISTA_PRESUPUESTO,
							PERFIL_JEFE_PRESUPUESTO,
							PERFIL_ASISTENTE_EJECUTIVO,
							PERFIL_DIRECTOR_EJECUTIVO,
							PERFIL_ASISTENTE_PRESIDENCIA,
							PERFIL_PRESIDENTE
						)
					)
			)
		);
?>