<?php 
/*REQUISICIONES*/
define("TIPO_BUSQUEDA_REQUISICIONES","1");
define("TIPO_BUSQUEDA_COTIZACIONES","2");
define("TIPO_BUSQUEDA_ORDENES_DE_COMPRA","3");

define("TIPO_DESTINO_TODAS","0");
define("TIPO_DESTINO_OFICINA_PRINCIPAL","1");
define("TIPO_DESTINO_INFOCENTRO","2");
define("TIPO_DESTINO_INFOMOVIL","3");
define("TIPO_DESTINO_OTRO","4");

define("TIPO_REQUISICION_TODAS","0");//TODAS
define("TIPO_REQUISICION_COMPRA","1");//PARA REQUISICIONES DE COMPRA
define("TIPO_REQUISICION_SERVICIO","2");//PARA REQUISICIONES DE COMPRA
define("TIPO_REQUISICION_MATERIAL","1");//PARA REQUISICIONES DE ALMACEN
define("TIPO_REQUISICION_BIEN","2");//PARA REQUISICIONES DE ALMACEN

define("TIPO_PROVEEDORES_TODO","1");
define("TIPO_PROVEEDORES_UNO","2");
define("TIPO_PROVEEDORES_MATRIZ","3");

define("ESTADO_REQUISICION_PENDIENTES","1");
define("ESTADO_REQUISICION_ENVIADAS","2");
define("ESTADO_REQUISICION_ENVIADAS_POR_OTROS","3");
define("ESTADO_REQUISICION_APROBADAS","4");
define("ESTADO_REQUISICION_DEVUELTAS","5");
define("ESTADO_REQUISICION_NO_REVISADAS","6");
define("ESTADO_REQUISICION_ANULADAS","7");
define("ESTADO_REQUISICION_TODAS","8");
//define("ESTADO_REQUISICION_SALIDA_COMPRA","9");
//define("ESTADO_REQUISICION_SALIDA_ALMACEN","10");
define("ESTADO_REQUISICION_DEVUELTAS_POR_USUARIO","11");
define("ESTADO_REQUISICION_EN_BORRADOR","12");

/*
//NO SE ESTA USANDO
define("COMP_ALM_PENDIENTE","0");
define("COMP_ALM_ALMACEN","1");
define("COMP_ALM_COMPRA","2");
*/

define("NA","0");

define("CALIDAD_BAJA","1");
define("CALIDAD_MEDIA","2");
define("CALIDAD_ALTA","3");

define("TIEMPO_ENTREGA_MENOR_7_DIAS","1");
define("TIEMPO_ENTREGA_MENOR_2_SEMANAS","2");
define("TIEMPO_ENTREGA_MENOR_1_MES","3");
define("TIEMPO_ENTREGA_MAYOR_1_MES","4");

define("GARANTIA_SI","1");
define("GARANTIA_NO","2");

define("ACCION_APROBAR_REQUISICION","1");
define("ACCION_DEVOLVER_REQUISICION","2");
define("ACCION_ANULAR_REQUISICION","3");
define("ACCION_ENVIAR_REQUISICION","4");
define("ACCION_GUARDAR_REQUISICION_EN_BORRADOR","5");

define("OBJETO_AGREGAR_INFORMACION","3");
define("OBJETO_REVISAR","4");

//TODO: COLOCAR RUTA ABSOLUTA
define("PDF_PATH","../../tmp/pdfFile.pdf");
define("PDF_PATH_PRE","../../tmp/pdfFile");
define("PDF_PATH_POS",".pdf");

define("ESTADO_ACTIVO","1");
define("ESTADO_INACTIVO","2");
define("ESTADO_TRANSITO","10");
define("ESTADO_ANULADO","15");

define("TIPO_IMPUTACION_ACCION_CENTRALIZADA","0");
define("TIPO_IMPUTACION_PROYECTO","1");
/*FIN REQUISICIONES*/

/*BALANCE GENERAL*/
define("BALANCE_GENERAL_NIVEL_TODOS","1234567");
/*define("BALANCE_GENERAL_NIVEL_UNO","1");
define("BALANCE_GENERAL_NIVEL_DOS","1237");
define("BALANCE_GENERAL_NIVEL_TRES","1347");
define("BALANCE_GENERAL_NIVEL_CUATRO","1247");*/
define("BALANCE_GENERAL_NIVEL_UNO","1");
define("BALANCE_GENERAL_NIVEL_DOS","12");
define("BALANCE_GENERAL_NIVEL_TRES","123");
define("BALANCE_GENERAL_NIVEL_CUATRO","1234");
define("BALANCE_GENERAL_NIVEL_CINCO","12345");
define("BALANCE_GENERAL_NIVEL_SEIS","123456");
/*FIN BALANCE GENERAL*/

/*COMUNICACIONES*/
define("BANDEJA_RECIBIDOS","1");
define("BANDEJA_ENVIADOS","2");
/*FIN COMUNICACIONES*/
?>